"""Render the local data-preparation findings from measured JSON evidence."""
import json
from pathlib import Path
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]

def read(name):return json.loads((HERE/name).read_text(encoding='utf8'))
def write(path,text):path.write_bytes((text.strip()+'\n').encode())

def main():
    sources=read('source_manifest.json');s=read('statistics.json');r=read('rejection_stats.json')
    t=read('tokenizer_evidence.json');l=read('leakage_audit.json');a=read('shortcut_audit.json');p=read('runtime_projection.json')
    e=read('experiment.json');dry=read('dry_run_evidence.json')
    attribution=['# External Auditor dataset attribution','',
        'The transformed external text is attributed to Salesforce and the cited dataset authors under CC-BY-4.0. This data license is separate from repository code licensing. Changes made here: reversible formatting, exact executable replacement, exact span deletion, and adjacent insertion. No endorsement by the upstream authors is implied.',
        '', 'License: https://creativecommons.org/licenses/by/4.0/ ; the full legal text and dataset cards are preserved in `tuning/auditor_external_relation_v1/licenses/`.']
    for src in sources:
        attribution+=['',f"## {src['dataset']}",'',f"Publisher: {src['publisher']}. License: {src['license']}. Revision: `{src['revision']}`.",
            f"Repository: https://huggingface.co/datasets/{src['dataset']}",
            f"Paper: [{src['citation']['title']}]({src['citation']['url']}).",
            'Authors: '+', '.join(src['citation'].get('authors',[]))+'.' if src['citation'].get('authors') else 'Paper identity is linked from the official Salesforce factualNLG repository.',
            f"Downloaded rows: {src['rows']}; unique normalized underlying documents: {src['unique_normalized_documents']}.",
            f"Raw SHA-256: `{src['files'][0]['sha256']}`.",
            f"Downloaded at: `{src['files'][0]['downloaded_at']}`.",
            'Raw schema: `'+json.dumps(src['schema'],sort_keys=True)+'`.',
            f"Use: {src['conversion_use']}."]
    attribution+=['','Every external row carries dataset, publisher, revision, license and link, citation, upstream row ID, upstream document ID, canonical document hash, original-row hash, source hash, upstream edit type/model, and a modification notice. `document_registry.jsonl` preserves row-hash/document-group lineage for both downloaded sources. SummEdits has no doc_id field; its registry retains null upstream doc_id and a content-derived document hash rather than inventing an upstream identifier.',
        '', 'The upstream datasets include model-generated summaries/edits. No new model generation, LLM annotation, per-row agent labeling, or paraphrasing was performed in this preparation task. Upstream factual-consistency labels and explanation text were not used as Shimmer relation labels.',
        '', 'The official HF cards both declare CC-BY-4.0. The separate factualNLG code repository displays Apache-2.0; that code license was not substituted for the downloaded HF data license. Its README is retained only in ignored raw documentation storage, with a download hash in the license manifest.']
    write(ROOT/'docs/fix/AUDITOR_EXTERNAL_DATA_ATTRIBUTION.md','\n'.join(attribution))
    lines=['# Auditor external relation data V1','', '`AUDITOR_EXTERNAL_RELATION_DATA_V1_NOT_READY`','',
        'The acquisition, deterministic converter, grouped splits, tokenizer dry-run, merged view, and prospective classifier configuration are complete. The 208-row candidate is frozen as a **quarantine/analysis artifact**, not admitted training data. The specified quartet design exposes a 75% word-count-sign shortcut on both TRAIN and DEV, and only 52 independent documents survive the conservative rules. HOLDOUT remains unconsumed.',
        '', '## Motivation and preserved evidence','',
        'The preceding frozen-representation linear probe fit TRAIN perfectly but obtained canonical DEV macro F1 0.679320 and accuracy 41/60. More diverse labeled data could test scarcity/coverage against a representation limitation. This task makes no model-quality claim and changes none of the canonical Auditor, linear-probe, or Producer results. All three prior evidence manifests were rechecked against their text files before and after preparation; model/feature binaries were not opened.',
        '', '## Upstream acquisition','',
        '| Source | Rows | Normalized documents | Upstream doc IDs | License |',
        '|---|---:|---:|---:|---|']
    for src in sources:
        lines.append(f"| {src['dataset']} | {src['rows']} | {src['unique_normalized_documents']} | {src['unique_upstream_doc_ids'] if src['unique_upstream_doc_ids'] is not None else 'not supplied'} | {src['license']} |")
    lines+=['','Both exact schemas and row counts match the request. SummExecEdit has 218 distinct raw doc_id values: 217 non-placeholder IDs plus `N/A`, which occurs on 2,120 rows. Placeholder IDs were excluded from identity unions. Exact normalized document content is authoritative for deduplicating ID aliases. Both datasets contain the same 216 normalized document texts; SummEdits is retained as a future pool, not counted as extra independent coverage.',
        '', 'Full revisions, download timestamps, sizes, raw/card SHA-256 identities and exact field/type schemas are in `source_manifest.json`. Only public dataset files, dataset documentation and license text were downloaded; no authentication was used. Raw JSON is ignored under `data/external/auditor_relations/raw/`.']
    for src in sources:lines+=['',f"{src['dataset']} revision `{src['revision']}`; raw SHA-256 `{src['files'][0]['sha256']}`."]
    lines+=['','See [attribution](AUDITOR_EXTERNAL_DATA_ATTRIBUTION.md) for source links, citations, licenses and modification notices.',
        '', '## Mechanical conversion and rejection','',
        'Factual consistency against the original upstream document is not identity or a Shimmer relation between two summaries. No upstream label was mapped directly. A lineage must have a unique exact source span and a byte-exact executable replacement, with nonempty substantive text. Normalization-only changes and word-subsequence insertions/deletions disguised as replacements are rejected. Both spans must be complete sentence-like units with at least five lexical words; deleting the original span must leave a sentence-like remainder. Obvious leading dangling pronouns/connectives, unbalanced delimiters, reserved transport strings, and pre-existing replacement text are rejected.',
        '', 'Each quartet uses the same original summary. MATCH changes only a reversible wrapper; DIVERGENCE uses the exact verified edited summary; OMISSION removes exactly the designated span without global cleanup; ADDITION retains every source byte and inserts the exact replacement immediately after the original span, with a separating space. No sentence is paraphrased, reordered or summarized. Every emitted candidate is checked against its mechanically reconstructed expected value. Entire quartets are filtered together.',
        '', f"Mechanically eligible: {r['mechanically_eligible_base_lineages']} base edits from {r['eligible_unique_docs']} documents. Selected: {s['quartets']} quartets / {s['rows']} rows. Rejected or not selected: {r['rejected_rows']} upstream rows. Reasons are exclusive first-failure categories:",'',
        '| Reason | Rows |','|---|---:|']
    for reason,count in sorted(r['reasons'].items()):lines.append(f'| {reason} | {count} |')
    lines+=['','All 6,348 SummEdits rows are audited source-pool records, not rejected quartet attempts. No quotas are filled from its consistency labels. Of emitted rows, 25% are direct verified executable replacements and 75% are deterministic identity/deletion/insertion derivatives; all 100% retain the executable-edit lineage.',
        '', '## Diversity and split','',
        f"There are {s['unique_docs']} distinct upstream documents, {s['unique_document_hashes']} normalized document hashes, {s['unique_source_hashes']} source-summary hashes and {len(s['domains'])} domains. Each document contributes exactly four rows (one quartet). No document is counted as independent multiple times. There are six rendering pairs, each applied identically across sibling classes. These are conservative single-item plain/bullet/numbered wrappers, so structural coverage is modest.",'',
        '| Class | Rows | Mean source words | Mean candidate words | Mean word ratio | Mean prompt tokens |',
        '|---|---:|---:|---:|---:|---:|']
    for c,v in s['by_class'].items():lines.append(f"| {c} | {v['rows']} | {v['source_words']['mean']:.2f} | {v['candidate_words']['mean']:.2f} | {v['word_length_ratio']['mean']:.3f} | {v['prompt_tokens']['mean']:.2f} |")
    lines+=['','Domain row counts: '+json.dumps(s['domains'],sort_keys=True)+'.',
        '', 'Rendering pair row counts: '+json.dumps(s['rendering_pairs'],sort_keys=True)+'.',
        '', 'Every class has exactly the same source, domain and renderer distribution. Detailed source/candidate character and tokenizer distributions, prompt distributions and ratios are in `statistics.json`.',
        '', '| Split | Rows | Docs | Quartets |','|---|---:|---:|---:|']
    for split in ['train','dev','holdout']:
        v=s['by_split'][split];lines.append(f"| {split.upper()} | {v['rows']} | {v['docs']} | {v['quartets']} |")
    lines+=['','Document groups are formed before final example emission using non-placeholder upstream ID links, normalized full-document identity across datasets, exact source/candidate duplicates and token 5-gram Jaccard >=0.80 connected components. Hash-ordered group assignment gives approximately 80/10/10. All upstream rows have a frozen registry entry, including reserved split membership for corresponding SummEdits documents. Every selected sibling and document stays in one split. Selection is at most one base edit per document.',
        '', f"Cross-split exact normalized duplicates: {l['cross_split']['exact_cross_split_duplicate_pairs']}. Maximum cross-split token 5-gram Jaccard: {l['cross_split']['max_cross_split_5gram_jaccard']:.9f}. Pairs at or above 0.80: {len(l['cross_split']['near_duplicate_pairs'])}. Sources, candidates and underlying documents are included. Maximum overlap against historical TRAIN/DEV source/candidate text: {l['grouping']['historical_train_dev_max_5gram_jaccard']:.9f}. No high-overlap pair required exclusion. These lexical checks do not establish semantic independence.",
        '', '## Shortcut audit and readiness blocker','',
        'Opaque IDs are allocated as four independent slot hashes before a separately seeded per-lineage permutation assigns classes. Rows are globally sorted by a separate opaque hash. No label is encoded in an ID suffix or REF number. External reference lists are empty; the exact historical reference canonicalizer is reused. All outer metadata—including provenance, transformation trace, hashes, domain, IDs and relation—is excluded from prompts.',
        '', '| Descriptive bucket purity (oracle, not fitted model) | TRAIN | DEV |','|---|---:|---:|']
    for k in ['id_mod4','id_mod5','id_mod20','row_order_mod4','refs','renderer','domain','source_length_20word_bin','candidate_length_20word_bin','prompt_length_50token_bin','word_ratio_sign']:
        lines.append(f"| {k} | {a['train'][k]['oracle_bucket_accuracy']:.3f} | {a['dev'][k]['oracle_bucket_accuracy']:.3f} |")
    lines+=['','Sparse ID bins have high in-sample purity by chance, particularly with only 20 DEV rows. This is not held-out accuracy and no classifier was fitted. No tested ID/modulo/order feature deterministically recovers all labels. Domain, renderer, refs and source-length buckets are exactly balanced. The raw merged historical records deliberately retain their original fields; those known historical ID/REF shortcuts must remain excluded/canonicalized at prompt construction.',
        '', f"The predeclared fixed length rule (equal -> MATCH; shorter -> OMISSION; longer -> ADDITION; never DIVERGENCE) scores {a['train']['fixed_length_sign_rule']['accuracy']:.2%} on TRAIN and {a['dev']['fixed_length_sign_rule']['accuracy']:.2%} on DEV. HOLDOUT was excluded from baseline scoring. This is an analytical construction-level defect: in every complete quartet the rule gets MATCH, OMISSION and ADDITION correct, regardless of DIVERGENCE. Reweighting/reselecting complete quartets or changing harmless wrappers cannot reduce that 3/4 floor after wrapper removal. Artificial whitespace or token padding would merely conceal it. No such padding, extra same-document lineages, label remapping, or looser span rules were used to force readiness.",
        '', 'Reconstruction within the mandated quartet constraints therefore cannot eliminate the observed shortcut. This freeze records the failed admission candidate; it is not a ready corpus freeze. A future task needs a changed deterministic construction or an explicitly narrower contrast-task objective before the dataset can test the semantic-diversity hypothesis. Even apart from the shortcut, 208 rows and five DEV documents are useful for converter diagnostics but inadequate evidence for the requested substantial diversity expansion.',
        '', '## Tokenizer dry-run','',
        'Pinned local tokenizer: `unsloth/Phi-3.5-mini-instruct-bnb-4bit` revision `5c20803aa197416f43fb455e55c85178775320cb`. Tokenizer/config assets were hash-checked; no weights were opened. Prompts use the frozen Auditor instruction, V2 clarification, canonical input normalization and native chat template. No truncation.',
        '', '| Prompt set | Count | Min | Median | Mean | p95 | p99 | Max |','|---|---:|---:|---:|---:|---:|---:|---:|']
    for name,key in [('All prospective eligible quartet members','prospective_prompt_statistics'),('Frozen external candidate','release_prompt_statistics'),('Historical substantive TRAIN + DEV','historical_substantive_prompt_statistics')]:
        v=t[key];lines.append(f"| {name} | {v['count']} | {v['min']} | {v['median']} | {v['mean']:.2f} | {v['p95']} | {v['p99']} | {v['max']} |")
    lines+=['',f"Supported classifier input ceiling: {t['ceiling']}. Prospective overflows: {t['prospective_overflow_rows']}; released-candidate overflows: {t['release_overflow_count']}. No quartet was dropped for length. Combined explanation-output budgeting remains a separate future integration check.",
        '', '## Views and next experiment','',
        f"The merged view contains 240 unchanged historical TRAIN objects plus {e['train']['external_substantive']} external TRAIN rows, for {240+e['train']['external_substantive']} rows. Substantive TRAIN is 192 historical + {e['train']['external_substantive']} external = {e['train']['combined_substantive']}; all 48 historical INSUFFICIENT_EVIDENCE rows are preserved unchanged. No historical DEV row is merged.",
        '', '`AUDITOR_EXTERNAL_RELATION_CLASSIFIER_V1` is prepared but disabled: frozen refusal veto -> four-way substantive linear classifier -> conditioned explanation. The prospective head uses the same frozen Auditor/checkpoint-120 representation, final prompt-token vector of dimension 3072, TRAIN-only standardization, four outputs, 12,292 trainable head parameters, seed 7, 200 Adam updates at 0.01 with the prior 0.001 weight regularization. This configuration is a proposal, not execution tooling or authorization.',
        '', f"Primary DEV would contain {e['dev']['primary_external']} external rows; historical 48-row substantive canonical DEV remains a secondary distribution-shift diagnostic. HOLDOUT is excluded. Classifier gates remain macro substantive F1 >=0.75 and every class recall >=0.60; aspirational targets are 0.80/0.70. All frozen integrated Auditor gates and zero catastrophic errors are retained verbatim in `experiment.json`; no integrated evaluation was run. No classifier LoRA fallback is implemented, and success of a larger-data linear head is not assumed.",
        '', '## Runtime and cost projection only','',
        f"For this rejected candidate, feature extraction projects to {p['total_feature_seconds']:.2f} seconds: TRAIN {p['train']['feature_seconds']:.2f}s, external DEV {p['external_dev']['feature_seconds']:.2f}s, historical DEV {p['historical_dev']['feature_seconds']:.2f}s. This scales the measured 227,276 prompt tokens / 86.1036 seconds by the actual planned prompt-token total, not row count alone. After feature caching, head inference is budgeted at 0.01-1 second for each DEV set (unmeasured).",
        '', f"The 200-update head calculation projects {p['head_200_update_seconds_linear_scaling']:.2f}s from the historical 0.462s, scaled by TRAIN rows and four rather than five outputs; reserve 1-5s because tiny GPU operations have fixed overhead. Expected peak allocation is roughly 3.56-4.5 GiB; reserve 6 GiB. Warm classification-only compute is about {p['warm_gpu_compute_minutes']:.2f} minutes. With provisioning, environment preparation and transfers, plan 10-20 A10 minutes / $0.215-$0.43 using the prior $1.29/hour rate. These are projections, not current price verification, a hard bound, or cloud authorization. Veto/explanation generation is excluded; the prior 48 explanations alone took 279.56s and would dominate integrated evaluation.",
        '', '## Validation and boundaries','',
        'Validation covers source hashes/counts/exact schemas/license cards, executable edit reproduction, complete balanced quartets, reverse rendering, provenance round-trip, document cap, sibling containment, cross-dataset identity, lexical duplicates, token ceiling, unchanged historical rows, and separate HOLDOUT denial. Invalid fixtures cover empty/repeated spans, hidden edits, normalization-only changes, disguised insertion, partial clauses, empty deletion, dangling pronouns, and tampered candidates. Additional tests cover lexical grouping, renderer reversibility, prompt metadata exclusion, REF renaming, overflow detection, and runtime denial hooks. Both original-order and reversed-order reconstruction produce identical row/rejection identities; whole-artifact rebuild hashes are recorded separately.',
        '', 'The strict sentence-like filter is a mechanical approximation: it cannot prove every grammatical/coreference condition or detect every semantically equivalent replacement. Single-item wrappers offer limited structural variety; scitldr supplies no admitted quartet. These limitations further prevent treating this small diagnostic corpus as a successful test of the data-scarcity hypothesis.',
        '', 'HOLDOUT has frozen labels and structural/token/lexical integrity checks only. No prediction, classifier baseline, model inference, or evaluation was performed on it. The receipt remains `consumed=false`; the accessor denies all execution while data admission is false. All existing historical text evidence passed preservation checks.',
        '', 'Confirmed: public dataset/documentation/license downloads only; no new LLM labeling, per-row agent generation, cloud compute, model generation/inference, model weights, training, Producer execution, protected access, folds1-4 execution, paid API, full pipeline, multi-round run, or push.',
        '', '`AUDITOR_EXTERNAL_RELATION_DATA_V1_NOT_READY`']
    write(ROOT/'docs/fix/AUDITOR_EXTERNAL_RELATION_DATA_V1.md','\n'.join(lines))

if __name__=='__main__':main()
