"""Render the quantitative local design report from frozen-input audit artifacts."""
from local_common import *
from statistics import median
from release import preservation

def run():
    a=read(HERE/'failure_audit.json');s=read(HERE/'statistics.json');spec=read(HERE/'experiment.json')
    token=read(HERE/'token_analysis.json');p=read(HERE/'projection.json');review=read(HERE/'review_adjudication.json')
    leakage=read(HERE/'leakage_audit.json');dry=read(HERE/'dry_run_evidence.json');history=preservation()
    assert dry['passed'] and review['passed'] and dry['dataset_sha256']==sha(HERE/'dataset.json')==spec['dataset_sha256']
    lines=['# Producer targeted failure audit and V3 design','',
        '**PRODUCER_TUNING_V3_DESIGN_READY**. This is a local design/curation/tokenizer dry-run verdict, not permission to train or a quality result. The completed V2.1 checkpoint-120 result remains **PRODUCER_CHECKPOINT120_FAIL**. This is the last automatic Producer redesign cycle.','',
        'V2 saved measurements: fresh 60/60; 35 accepted and complete; contract/claims/evidence 1.0; uncertainty F1 0.909090909; gap F1 0.760180995; refusal precision 0.571428571, recall 1.0, over-refusal 0.053571429. Seven refusals comprise four correct and three false. All six catastrophic categories are zero. The audit reads saved verdicts/metrics and compares raw atoms; it never calls the historical scorer or changes prior labels, outputs, verdicts, releases or Auditor design.','',
        'Every failed row is listed below. Full owned source, expected/observed structures, saved metrics and every diagnostic atom pairing are retained in [failure_audit.json](../../tuning/producer_v3/failure_audit.json). All IDs have prefix `shimmer2-producer-document-`.','',
        '| Failed ID | Rendering | Diagnostic tags | Atom corrections |','|---|---|---|---:|']
    for r in a['failed_rows']:lines.append(f"| {r['example_id'][-3:]} | {r['features']['rendering_template']} | {', '.join(r['tags'])} | {r['semantic_atom_corrections']} |")
    lines+=['','Tags are multi-label. `missing_gap` means an exact required gap atom is absent, including a mislabelled replacement; it does not imply pure omission. `partially_missing_gap_set` means at least one exact gap survives and at least one is absent. `status_inconsistency` includes a whole-packet false refusal.','',
        '| Error tag | Failed rows |','|---|---:|']
    for k,v in a['failure_tags'].items():lines.append(f'| {k} | {v} |')
    c=a['completeness']
    lines+=['',f"Of 22 failed non-refusal outputs, 21 preserve all claims but have a gap deficit; one fails only uncertainty referent assignment. Across all failures, 24 preserve all claims yet lack at least one exact gap. Three fail through refusal. Three miss uncertainty and three contain extra uncertainty (including cross-kind substitutions). Nineteen have partially correct gap sets. **15/25 (60%) are one-atom corrections away; nine require two and one requires three.** A substitution is one correction despite contributing both FP and FN; moving gap/uncertainty kind is also one correction. This is diagnostic edit distance, not predicted V3 performance. No hypothetical repaired output is scored or accepted.", '',
        '**Gap decomposition: TP=84, FP=20, FN=33**, giving 168/221 = 0.760180995 F1. Each FN and FP receives exactly one primary class below. Minimum-field-distance pairing is an explicit diagnostic convention; a compound replacement can carry several row tags. Pairing does not change frozen exact-string counts.','',
        '| Primary class | FN | FP |','|---|---:|---:|']
    for k in a['gap_error_classes']['fn']:lines.append(f"| {k} | {a['gap_error_classes']['fn'][k]} | {a['gap_error_classes']['fp'][k]} |")
    fnattrs=Counter(e['expected']['attribute'] for r in a['failed_rows'] for e in r['atom_edits'] if e['expected'] and e['expected']['kind']=='gap')
    lines+=['','FN attributes: '+', '.join(f'{k}={v}' for k,v in fnattrs.most_common())+'.', '',
        'The deficit is concentrated: recording-time (9), event-time (7), order (4) and recording-occurrence (4) account for 24/33 FN. Ten paired referent errors include six event-time atoms changed from the frozen `owned_record` referent to `event`, plus observation, recorder and submission referents. Thirteen pure omissions include six atoms lost to the three refusals and seven omissions in extracted outputs. Errors also mix recording occurrence with entry presence, recording time or submission occurrence, and move atoms between gap and uncertainty. No broad claim/evidence/contract degradation is observed. The representational convention for an event date is preserved even though ordinary English could suggest an event referent; this design does not silently change the ontology.','',
        '**Three over-refusals, inspected individually:**','',
        '| ID | Source-visible supported content | Length (characters) | Existing TRAIN occurrences of exact typed gap |','|---|---|---:|---|']
    descriptions={'054':'event time missing + reporting time unspecified','138':'observation time missing + later-entry order question','152':'reporting time unspecified + first-entry explicit absence'}
    for r in a['refusal_cohorts']['false_refusal']:
        lines.append(f"| {r['example_id'][-3:]} | {descriptions[r['example_id'][-3:]]} | {r['source_chars']} | "+', '.join(f"{g['attribute']}={g['count']}" for g in r['gold_gap_train_occurrences'])+' |')
    lines+=['',
        'All three have one owned span, two supported gaps, no uncertainty, no CLM claims, no refs, and the regulation domain. Their renderings are timeline, register and machine-log. None needs an unknown gap type or outside knowledge; all required atom types already occur in TRAIN. Explicit missingness/order/absence is extractable information. These cases do not justify packet-specific or regulation-specific exceptions.','',
        'The four correct refusals (059, 149, 164, 284) explicitly state an unavailable quantitative value outside the finite ontology, alongside a supported gap. They also have one span and no claims/refs/uncertainty. Lengths are 130, 135, 137 and 147 characters; the false-refusal lengths are 114, 131 and 134. Thus absent refs, missingness words, and short sources cannot define the refusal rule. A supported clause elsewhere does not authorize dropping an unrepresentable owned proposition.','',
        'Among the 49 substantive non-refusals: nine have no claims/refs, 16 have no uncertainty, 36 have two gaps, 13 have three, 23 have two spans, and five contain conflicting claims. Two are regulation examples; five regulation substantive rows total give 3/5 false refusals versus 0/47 elsewhere. This is a small, confounded correlation, not evidence of a domain cause. Their source lengths range 165–432 characters. The three false refusals are shorter than this cohort, but length is confounded with absent claims/refs/uncertainty. All 60 DEV rows belong to the anchored structural superfamily, so family-specific causation cannot be estimated from this evaluation. Multiple gaps are common in both success and failure; uncertainty and multiple/conflicting claims are absent from these three false refusals.','',
        'Domain-agnostic diagnosis: distinguish source insufficiency/unrepresentable semantic content from explicit supported missingness. Preserve every supported gap even with zero claims/refs; refuse only when the full owned proposition/referent cannot be represented or resolved under the unchanged policy. The observed concentration motivates data contrasts, not a causal claim about weights or a new inference-time exception.','',
        '**Targeted data:** retain all 300 Producer V2 rows unchanged (260 substantive, 20 refusal controls, 20 empty controls). Add 100 substantive rows and 20 genuine refusal controls. There are 360 unique substantive atom sets after removing names, quantities, claims, refs, surface wording and owner aliases; expansion credit is not assigned for domain/template renaming. All additions have new document families, entities, domains, wording and source organization. Authoring uses abstract error classes and checks old signatures for exclusion; no failed DEV packet is a training parent.','',
        'Twenty hard contrast pairs share document/derivation ancestry: five unavailable-magnitude vs supported-missingness pairs; five unknown-temperature vs supported uncertainty/gaps pairs; ten ambiguous two-antecedent vs uniquely bound one-antecedent recording-relation pairs. The negative differs in semantic sufficiency, not the presence of generic missing/unknown words. Positive examples include 20 missingness-only cases without uncertainty; the other 80 combine gaps and uncertainty. Ten unsupported-content refusals and ten deictic-ambiguity refusals supplement the existing 20 genuine refusals. All pair siblings stay in one split.','',
        'The 100 new substantive examples combine two or three gaps with temporal-role/referent/nonoccurrence/order distinctions; varied claim/ref burdens and multiple ownership spans preserve completeness pressure. Twenty authored same-batch conflicting-claim cases retain both claim IDs instead of refusing. Two repeated source clauses are intentionally deduplicated into one target atom, as independently flagged by review. Every distinct required atom is retained; deleting one fails local label validation. The production contract, compact rendering and finite ontology are unchanged.','',
        '| Corpus quantity | V3 total | TRAIN | DEV |','|---|---:|---:|---:|']
    totals=s['total'];tr=s['split']['train']['producer'];dv=s['split']['validation']['producer']
    for key in ('rows','substantive','document_families','template_families','refusals','gap_bearing','uncertainty_bearing','multi_span','multi_claim'):
        lines.append(f'| {key} | {totals[key]} | {tr[key]} | {dv[key]} |')
    lines+=['',f"Non-refusals: {totals['rows']-totals['refusals']} total / {tr['rows']-tr['refusals']} TRAIN / {dv['rows']-dv['refusals']} DEV. Twenty domains: ten unchanged V2 domains and railway, theatre, horticulture, geology, manufacturing, navigation, textiles, acoustics, ceramics and cartography. Five conservative structural superfamilies are retained; new sectioned packet organizations inherit the existing sectioned TRAIN group and explicitly anchored envelope faces inherit the anchored DEV group. There are25 rendering layouts total (20 retained +5 new); renamed layouts do not earn new structural independence. There are 400 document families because each new contrast pair shares a family. Document IDs do not establish statistical independence.", '',
        '| Gap attribute | Atoms |','|---|---:|']
    for k,v in totals['gap_attributes'].items():lines.append(f'| {k} | {v} |')
    lines+=['',f"Grouped canonical split: **336/84 (80/20)**. Keep all old 240 TRAIN/60 DEV memberships. The original conservative group assignments place all24 new anchored `{read(HERE/'split.json')['held_out_new_structure']}` rows in DEV and all96 new sectioned rows in TRAIN. We do not call five framing variants independent structural superfamilies. All document/template/derivation/paraphrase/renaming/leakage-group intersections are empty, all 20 contrast pairs remain together, and normalized substantive semantic signatures do not cross the split. Maximum new-to-old-DEV normalized source five-gram Jaccard is {leakage['max_new_to_old_dev_fivegram_jaccard']:.6f}. This lexical screen is descriptive, not proof of independence. V3 DEV is a development set after failure-informed design, not an untouched final benchmark. No folds1–4 are built or run.", '',
        '| Target token lengths, including native assistant termination | Count | Min | Median | Mean | p95 | Max |','|---|---:|---:|---:|---:|---:|---:|']
    for key in ('refusal_targets','substantive_targets'):
        d=token[key];lines.append('| '+key+' | '+' | '.join(f'{d[k]:.6f}' for k in ('n','min','median','mean','p95','max'))+' |')
    lines+=['',
        'TRAIN contains 32 genuine refusals and 304 non-refusals (288 substantive plus16 empty), so refusal learning is retained. Balanced hard cases teach why similar absence/uncertainty surface cues can demand extraction. Target-length accounting is for the local training tokenizer and includes native termination; it is not measured generated-output efficiency.','',
        '**Machine curation:** a fresh input-only agent reviewed all120 opaque-ID packets, independently specified a 29-clause atom mapping, and preserved every owned claim/ref/atom without calling the author interpreter as an oracle. Final authored labels and independent predictions agree on all120 statuses and owned atoms, claims and refs. Exact supports pass the established frozen finite-policy validator. A separate initial curation saw status-bearing IDs before they were replaced, so it is explicitly not called fully blind; only the fresh opaque-ID review satisfies the blindness check. Review files, scripts, input hashes and adjudication are retained.','',
        '**Machine curated; not human reviewed; not independent final benchmark evidence.** Synthetic repeated English clauses and five new framing patterns provide targeted compositional diversity, not broad natural-language generalization. Reviewers share the frozen ontology and filesystem; there is no OS isolation or independent ontology-validation claim. No protected data were used.','',
        '**Exactly one configuration: DATA-ONLY.** Claims/evidence and contract already pass, uncertainty is strong, and gap/refusal errors concentrate in interpretable structures. Nothing measured isolates rank, LR or objective as the cause. Therefore retain rank/LR/objective, not a sweep. Fresh base + fresh adapter initialization; the failed V2 adapter is preserved and is not a V3 initializer.','',
        '| Configuration | Frozen value |','|---|---|',
        f"| Model | `{spec['model_id']}` |",f"| Revision | `{spec['revision']}` |",f"| Dataset | `{spec['dataset_version']}`, SHA256 `{spec['dataset_sha256']}` |",
        '| LoRA | rank8, alpha16, dropout0.05, bias none, CAUSAL_LM |',
        '| Target modules | q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj |',
        '| LR / optimizer | 0.0001 / AdamW, betas0.9/0.999, epsilon1e-8, weight decay0 |',
        '| Objective | Per-example mean assistant-target plus native termination cross entropy; equal example weights |',
        '| Passes / updates | 2 full TRAIN passes /168 optimizer updates |',
        '| Microbatch / accumulation | 1 /4; effective batch4, no remainder |',
        '| Scheduler | linear, warmup1 update; seed7; max gradient norm1 |',
        '| Checkpoints | 84 and168; one complete DEV evaluation per pass |',
        '| Training runtime | gradient checkpointing; BF16; eager attention; deterministic algorithms; TF32 disabled |',
        '| Quantization | existing pinned NF4 4-bit with double quantization and BF16 compute |',
        f"| Sequence ceiling | 992, unchanged; observed local maximum{token['max_sequence']}; no truncation |",
        '| Generation | greedy, batch1, no sampling, one beam, cache true, max_new_tokens288; EOS[151645], pad151654 |',
        '| Base weight SHA256 | `99b85155b7bb40344d8c3938c8ec1147b27028804bca5d2e5559cb8e6533747d` (historical binding; no weights read) |',
        '| Authorization | false; local design and dry-run only |','',
        'Only data population and its mechanical schedule bindings change: 240->336 TRAIN, 60->84 DEV, 60->84 updates/pass, 120->168 total updates, checkpoints[60,120]->[84,168]. All mathematical optimization hyperparameters and the two-pass exposure remain unchanged. The scheduler horizon follows the unchanged two-pass rule. Generation/prompt/tokenizer/contract/quality thresholds are unchanged.','',
        '| Quality gate | Required |','|---|---|']
    for direction,values in spec['selection_gates'].items():
        for k,v in values.items():lines.append(f'| {k} | {">=" if direction=="minimum" else "<="} {v} |')
    lines+=['| Six catastrophic categories | each zero |','',
        'Undefined or nonfinite required metrics fail closed. Both checkpoints must have complete84-row evidence before selection. Among passing checkpoints, prefer completeness, then gap F1, then earlier step and adapter hash. If neither passes, stop the Producer LoRA branch; do not create V4 automatically. Token efficiency never overrides a quality failure. Future observations retain output median/p95, correct semantic atoms/token (claims/gaps/uncertainty/evidence separately), EOS-before-cap, duplicates, trailing prose and accepted-output token cost separated into correct refusal/empty versus substantive successes. No shortening objective or cap reduction is introduced.','',
        '**Runtime integration:** [runtime_binding.py](../../tuning/producer_v3/runtime_binding.py) pins unchanged runtime V2.1 SHA256 `8d1fd41d1ab059e47b1297c1c39cd29711acd8fa5446a60780f9a97faef1d1fa`. Prepared84-row prompts/IDs/masks are bound and validated with its exact record/generation validators. State-only local preflight exercises its actual corrected context, including generation_config=None and exact restoration, without any generation. Future execution must repeat real-object context preflight after adapter load, then cache probes before controls and full DEV.','',
        'The historical V2.1 authorization/session harness hardcodes checkpoint120 and60 rows; it is not reused as a V3 harness. V3 specifies steps84/168 and84 rows and implements a tested metadata sink that assigns correct V3 checkpoint/adapter/prompt identities before durable raw persistence. Generation mechanism remains the frozen low-level evaluate_records context with reference_trace=None; scoring follows raw persistence. A future training/cloud executor is intentionally absent and requires separate authorization and integration review. Design readiness does not claim deployment readiness.','',
        'Cost-sensitive controls use two optimized passes on six prospectively fixed IDs at each checkpoint, requiring exact tokens/decoded text/semantic results/stop reasons, positive finite timing and the retained4.438538339317307 tok/s floor. No global sys.settrace, profiling or in-process telemetry is introduced. The historical six reference-vs-optimized controls and4.629896x observer-removal proof remain unchanged evidence; a second paired2x test between two optimized passes would be logically inapplicable. Future telemetry is separate-process. Any context/cache/control/speed failure is NO_GO with collection/teardown, not retraining or a retry.','',
        '**Future runtime/cost projection, not a current price quote or authorization:** retain both full per-pass DEV checks. The first can detect refusal collapse while the final enables overfit/collapse comparison; removing it would materially reduce diagnostic evidence. There is no additional post-training full re-evaluation of the same saved outputs.','',
        f"Historical training:118 clean inter-update intervals (exclude the first unanchored warmup timer and step61's embedded DEV pause), median {p['historical_training_step_seconds']['median']:.6f}s and p95 {p['historical_training_step_seconds']['p95']:.6f}s per four-example update. Training sequence-length ratio V3/V2={p['sequence_length_ratio']:.6f}. Projected168-update training={p['training_seconds']/60:.2f}min. Measured V2.1 prefill-inclusive throughput={p['observed_v21_full_rate']:.6f} output tok/s. V3 DEV target lengths mean {p['expected_dev_target_tokens']['mean']:.3f}, median {p['expected_dev_target_tokens']['median']}, p95 {p['expected_dev_target_tokens']['p95']:.2f}; these are output-length proxies, not generated predictions.", '',
        f"Two full DEV evaluations (168 outputs),24 control outputs and a four-probe cap allowance project {p['evaluation_seconds']/60:.2f}min evaluation. Including15min setup/collection/teardown reserve: **{p['total_seconds']/60:.2f}min, ${p['total_cost_at_historical_1_29_per_hour']:.4f} at the historical $1.29/hour A10 rate**. A deliberately conservative bound using training p95, all196 generations at288 tokens and the4.438538 floor is **{p['conservative_seconds']/60:.2f}min / ${p['conservative_cost_at_historical_1_29_per_hour']:.4f}**. Neither is a guarantee; initialization, new output lengths, hardware and training throughput may differ. The conservative case exceeds the prior $3 run cap, so that old authorization cannot be carried forward. Any future run needs a fresh price/capacity/budget decision and hard watchdog, with no automatic instance launch.", '',
        f"Local validation passed:420 tokenizer encodings, exact target-only masking/native termination, maximum target263<=288 and sequence{token['max_sequence']}<=992, semantic labels, complete grouped split, every TRAIN example exactly twice across168 planned updates, no DEV in gradients, all120 fresh-review matches, runtime record/generation binding and context restoration. {len(dry['fault_injections_rejected'])} named invalid fixtures rejected, plus all quality-threshold/catastrophic/nonfinite selection fixtures. These are no-model checks, not training or performance tests.", '',
        f"Preservation: {history['historical_byte_hashes_verified']} prior tracked files byte-verified; two preserved adapter files checked by size/mtime only, with zero weight bytes opened. Protected receipt remains UNCONSUMED. A local import-name collision attempted a historical dry_run module; the guard blocked its protected-evaluator import before that file could be opened. Local module resolution was corrected. The initial read-only preservation inventory byte-hashed the historical protected-evaluator wrapper, protected_population manifest and not-admitted receipt without parsing them or executing the wrapper; subsequent preservation checks use metadata only. No protected target data were opened, and no protected evaluation ran.", '',
        '**Prospective final stop rule:** if a future valid V3 training/evaluation has no checkpoint passing every frozen quality gate, stop Producer LoRA. No automatic V4, additional data cycle, sweep or retraining. Return to architecture/model choice only under a separate task. An invalid infrastructure run does not become a quality pass and must not consume this rule as an excuse to alter gates.','',
        'No cloud, real/model generation, training, weight update, Auditor execution/design change, folds1–4, protected access, paid API, full pipeline, multi-round execution or push occurred. This release does not authorize any of them.','',
        'Reproduce local checks: `python -B tuning/producer_v3/dry_run.py`, `python -B tuning/producer_v3/leakage.py`, then `python -B tuning/producer_v3/release.py`. Authoring and sealing are one-time pre-freeze operations. Frozen outputs must not be edited after sealing. The dry-run is deterministic and must leave all bound hashes unchanged.','',
        'Artifacts: [V3 directory](../../tuning/producer_v3/), [configuration](../../tuning/producer_v3/experiment.json), [split](../../tuning/producer_v3/split.json), [review](../../tuning/producer_v3/blind_review/fresh_review.json), [local verification](../../tuning/producer_v3/dry_run_evidence.json), [freeze](../../tuning/producer_v3/freeze.json).']
    (ROOT/'docs/fix/PRODUCER_TUNING_V3_DESIGN.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
    write(HERE/'readiness.json',dict(verdict='PRODUCER_TUNING_V3_DESIGN_READY',historical_result='PRODUCER_CHECKPOINT120_FAIL',
        data_and_labels_ready=True,canonical_split_frozen=True,configuration_count=1,local_dry_run_passed=True,
        training_authorized=False,cloud_authorized=False,AUDITOR_STATUS='UNTOUCHED',PROTECTED_RECEIPT_STATUS='UNCONSUMED',preservation=history))
    (HERE/'HANDOFF.md').write_text('# Producer V3 local design handoff\n\nPRODUCER_TUNING_V3_DESIGN_READY\n\nHistorical checkpoint120 FAIL remains unchanged. Data-only augmentation:300+120 rows,360 substantive;336 TRAIN/84 DEV. One config:rank8 alpha16 dropout0.05 LR1e-4, two passes,168 planned updates, checkpoints84/168. Runtime V2.1 preserved; no future execution authorized. See ../../docs/fix/PRODUCER_TUNING_V3_DESIGN.md.\n\nLast automatic redesign: no passing V3 checkpoint -> stop Producer LoRA, no automatic V4; return to architecture/model choice. No cloud/model/training/Auditor/protected/folds1-4/API/full-pipeline/multi-round/push.\n',encoding='utf8')
    print('Report, readiness and handoff written')

if __name__=='__main__':run()
