"""Render preparation results from local evidence; no model or network access."""
from local_utils import *

def main():
    s=read(HERE/'statistics.json');a=read(HERE/'shortcut_audit.json');l=read(HERE/'leakage_audit.json')
    t=read(HERE/'tokenizer_evidence.json');p=read(HERE/'runtime_projection.json');e=read(HERE/'experiment.json')
    sources=read(HERE/'source_manifest.json');downloads=read(HERE/'download_manifest.json');rejections=read(HERE/'rejection_stats.json');ch=read(HERE/'dev_challenges.json')
    attribution=['# V2 external data attribution','',
        'PAWS-Wiki Labeled Final: Google LLC. Source repository https://github.com/google-research-datasets/paws ; downloaded Parquet from https://huggingface.co/datasets/google-research-datasets/paws at revision `161ece9501cf0a11f3e48bd356eaa82de46d6a09`. Original documentation revision `02b29f3af1143620d1b7f352247e65c0bdd2ec18`.',
        '',sources['paws']['citation'],
        '', 'PAWS uses the Google custom dataset notice permitting use for any purpose, with acknowledgement requested and no warranty. The exact text is in `licenses/paws-LICENSE.txt`; it is not relabeled as CC-BY.',
        '', 'WikiAtomicEdits: Google Research, https://github.com/google-research-datasets/wiki-atomic-edits at `1f6769f2f9d93b6bf5acb091eb509b2be36e8e79`.',
        '',sources['wikiatomic']['original_citation'],
        '',sources['wikiatomic']['sample_citation'],
        '', 'Published sample: PEER v1.0, authors Edison Marrese-Taylor, Machel Reid and Yutaka Matsuo, DOI https://doi.org/10.5281/zenodo.4478267 (concept DOI 4478266). The downloaded archive MD5 matches the publisher record: `8bca47b0019ce1ec33d332a73d7b3b75`. Only `PEER/edits/insertions_deletions.jsonl` and its split-ID files were extracted/read; other PEER datasets were not inspected.',
        '', 'The PEER paper describes sampling about 150K English WikiAtomicEdits records and retaining 104K after cleaning. The authors tokenize sentences, align edits and replace some numbers with placeholders. V2 drops placeholder-bearing text and retains exact token arrays joined with single spaces. The operation is derived from one contiguous published insert/delete tag run and validated against before/after arrays, changed tokens, source and target. No atomic operation is reversed.',
        '', 'License records differ: the official WikiAtomic README links CC-BY-SA-4.0 but contains the unrelated wording “Query-wellformedness dataset”; the PEER Zenodo record declares CC-BY-4.0; the HF sample card says unknown. We preserve all notices and both full Creative Commons license texts. We do not silently treat these statements as equivalent, discard upstream ShareAlike attribution, or substitute repository code licensing. The HF card was used for provenance documentation only; actual sample bytes came from the authors’ Zenodo archive. This is a preparation/quarantine release, not a legal determination resolving the differing notices.',
        '', 'Modifications in V2: selection, symmetric PAWS orientation, single-space joining of published WikiAtomic token arrays, opaque identifiers, metadata separation, grouping and new splits. Text was not paraphrased, padded or generated. Original human PAWS labels and WikiAtomic edit operations are retained; no new annotation was performed.',
        '', 'Every external row retains the source-pool key, original row ID/split, canonical raw-row SHA-256, orientation/operation, source file/member, license record, and SHA-256 binding to `source_manifest.json`. That manifest binds the download manifest with source URLs, revisions, timestamps and file hashes. No upstream Wikipedia article IDs are invented.']
    for name in ['paws-train.parquet','paws-dev.parquet','paws-test.parquet','PEER.zip']:
        d=downloads[name];attribution+=['',f"`{name}`: SHA-256 `{d['sha256']}`, {d['bytes']} bytes, downloaded `{d['downloaded_at']}` from {d['url']}."]
    (HERE/'attribution.md').write_bytes(('\n'.join(attribution)+'\n').encode())
    lines=['# Auditor external relation data V2','', '`AUDITOR_EXTERNAL_RELATION_DATA_V2_NOT_READY`','',
        'V2 preparation is complete. The word-sign hard gate passes and the requested balanced data views, challenge subsets, grouping, tokenizer evidence and classification-only experiment are prepared. Admission remains disabled under a conservative reading of the requested no-known-source-shortcut condition: source identity still separates the two class families, and source identity plus sign reaches 75% in a provenance oracle. This is not a demonstrated prompt-level exploit: dataset identity is excluded from prompts, and its inferability from text was not established. No stronger word-sign threshold is substituted and no model performance is claimed.',
        '', '## Source acquisition and policy','',
        'Original Google Storage URLs returned 403 AccessDenied for PAWS and both WikiAtomic English files. PAWS Labeled Final was obtained from the pinned Google Research Datasets HF repository. WikiAtomic uses the authors’ published PEER Zenodo sample, verified against its published archive checksum and hash-bound locally. No arbitrary scraped mirror, PAWS-QQP, noisy PAWS or swap-only data was used.',
        '', '| Source | Downloaded rows | Conversion pool | Retained |','|---|---:|---:|---:|',
        f"| PAWS-Wiki Labeled Final | 49,401 TRAIN + 8,000 DEV + 8,000 TEST | 49,401 official TRAIN | {s['by_class']['MATCH']['rows']+s['by_class']['DIVERGENCE']['rows']} |",
        f"| WikiAtomicEdits, published PEER sample | 104,000 (52,000 per operation) | 83,200 published TRAIN | {s['by_class']['OMISSION']['rows']+s['by_class']['ADDITION']['rows']} |",
        '', 'PAWS DEV/TEST were only hashed and inspected through Parquet footer row counts/schema; their label columns were not read. They do not source any V2 split. PEER valid/test IDs were excluded from conversion. New TRAIN/DEV/HOLDOUT are created from grouped upstream TRAIN pools. Thus neither original test set is turned into new training data.',
        '', 'PAWS fields are id:int32, sentence1:string, sentence2:string, label:int64 (human 0/1 judgment). The published WikiAtomic sample has id plus src, tgt, changed, src_tag, yin_before and yin_after arrays. Alignment tags provide the operation; full exact reconstruction is required. The source manifest records actual schemas, counts, revisions, raw hashes and licenses. See [attribution](../../tuning/auditor_external_relation_v2/attribution.md) for citations and the distinct Google/CC-BY/CC-BY-SA notices. Raw downloads remain ignored.']
    for name in ['paws-train.parquet','paws-dev.parquet','paws-test.parquet','PEER.zip']:
        lines+=['',f"{name}: `{downloads[name]['sha256']}`."]
    lines+=['','## Conversion and length controls','',
        'PAWS label 1 maps only to MATCH and label 0 only to DIVERGENCE. Orientation can be reversed because both upstream relations are symmetric; reversal is recorded. Equal-word-count PAWS pairs are excluded. Both sources require nonempty, sentence-like text of 8-60 lexical words, plausible sentence boundaries, balanced delimiters and no malformed markup/placeholders. This mechanical screening supplements PAWS Labeled Final human fluency judgments; it is not an LLM grammaticality review.',
        '', 'WikiAtomic requires exactly one contiguous insertion or deletion run, equal tokens unchanged, EMPTY markers only on the appropriate aligned side, and exact reconstruction of src/tgt and changed tokens. Pure punctuation/function-word-only edits are excluded. No atomic sentence is padded or relabeled, and no extra synthetic examples are created.',
        '', 'Groups are assigned before final sampling. Within each split and sign, common bins match abs(log(candidate/source word ratio)) in 0.025 steps and shorter-side word count in 10-word steps. Each selection unit draws one MATCH, one DIVERGENCE and two atomic examples from four distinct groups in the same bin. This yields equal overall class counts and matched magnitude-bin distributions. Units do not share semantic content or synthetic lineage.',
        '', '| Pool | Eligible before duplicate grouping | Rejection reasons |','|---|---:|---|']
    for name in ['paws','wikiatomic']:
        v=rejections[name];lines.append(f"| {name} | {v['eligible']} | {json.dumps(v['reasons'],sort_keys=True)} |")
    lines+=['', 'Pair duplicate/conflict audit: '+json.dumps(rejections['pair_dedup'],sort_keys=True)+'.',
        '', '## Final candidate corpus','',
        '| Class | Rows | Shorter / equal / longer | Mean source words | Mean candidate words | Ratio min / median / p95 / max |',
        '|---|---:|---|---:|---:|---|']
    for c in CLASSES:
        v=s['by_class'][c];q=v['word_ratio'];sg=v['signs']
        lines.append(f"| {c} | {v['rows']} | {sg.get('shorter',0)} / {sg.get('equal',0)} / {sg.get('longer',0)} | {v['source_words']['mean']:.2f} | {v['candidate_words']['mean']:.2f} | {q['min']:.3f} / {q['median']:.3f} / {q['p95']:.3f} / {q['max']:.3f} |")
    lines+=['',f"Total: {s['total']}; unique normalized pair/lineage groups: {s['unique_lineages']}. Both sources are Wikipedia-derived. Identical plain transport rendering is used for all classes. Detailed source/candidate words, word/character ratios and token statistics are in `statistics.json`. These are sentence lineages; unavailable article IDs prevent a claim of article-level independence.",
        '', '| Split | Rows | Per class | Unique lineages |','|---|---:|---|---:|']
    for split in ['train','dev','holdout']:
        v=s['by_split'][split];lines.append(f"| {split.upper()} | {v['rows']} | {json.dumps(v['classes'],sort_keys=True)} | {v['lineages']} |")
    lines+=['','## Leakage','',
        'Unordered normalized pairs bind reversed duplicates. Exact sentence-side matches and exact 5-gram Jaccard connections are unioned across both eligible source pools and historical Auditor TRAIN/DEV text before splitting. Any group touching historical text is excluded; at most one example per remaining group is selected. The original 0.80 threshold was tightened once to 0.50 after the first integrity audit found a cross-split similarity of 0.555556. This adjustment used lexical integrity, not model predictions or HOLDOUT performance.',
        '', 'Pool grouping: '+json.dumps(l['pool_grouping'],sort_keys=True)+'.',
        '', 'Final cross-split audit: '+json.dumps(l['final_cross_split'],sort_keys=True)+'.',
        '', 'No exact, reversed-pair or near-sentence lineage crosses the final splits. Lexical checks do not prove semantic independence. The complete eligible pool group registry is frozen so unselected siblings cannot later be silently assigned across splits.',
        '', '## Shortcut baselines','',
        '| Fixed rule | TRAIN accuracy | DEV accuracy |','|---|---:|---:|']
    for key in ['fixed_word_sign','fixed_ratio_threshold','fixed_source_dataset','fixed_source_and_sign_oracle','fixed_id_mod4','fixed_row_mod4']:
        lines.append(f"| {key} | {a['train'][key]['accuracy']:.4f} | {a['dev'][key]['accuracy']:.4f} |")
    lines+=['','The fixed sign rule predicts OMISSION for shorter, ADDITION for longer, MATCH for equal. It passes the <=0.55 DEV requirement; no sign rebalancing retry was needed. The fixed ratio rule uses <0.95 -> OMISSION, >1.05 -> ADDITION, otherwise MATCH. ID/order rules use four-way modulo with a predeclared class order. No classifier or embedding model was trained.',
        '', '| Descriptive oracle bucket purity | TRAIN | DEV |','|---|---:|---:|']
    for key in ['source_words_10bin','candidate_words_10bin','word_ratio_005bin','character_ratio_005bin','punctuation_counts','source_dataset','id_mod4','id_mod5','id_mod20','row_mod4','row_mod5']:
        lines.append(f"| {key} | {a['train'][key]['oracle_bucket_purity']:.4f} | {a['dev'][key]['oracle_bucket_purity']:.4f} |")
    lines+=['','Bucket purity is an in-sample oracle description, not fitted or held-out predictive accuracy. Dataset alone gives 50%; dataset plus sign gives 75% because the atomic classes become identifiable while PAWS remains two-way. Dataset name, operation, source file, upstream IDs, provenance and class labels never enter classifier prompts. The oracle is therefore a source-family confounding diagnostic, not proof of input leakage. We leave admission false rather than certify the no-known-source-shortcut requirement. Changing the mandated class/source mapping or explicitly accepting this controlled confound would require a subsequent scoped decision; no extra labels were invented here.',
        '', 'Opaque IDs hash normalized unoriented content identity with a fixed salt; they do not use class, source dataset, operation or row index. Row order uses a separate content hash. No tested ID/order bucket deterministically identifies all classes. References are empty, and the exact historical canonicalizer is reused.',
        '', '## DEV challenges','']
    for sign,c in ch.items():lines.append(f"- {sign.upper()}: {c['rows']} rows, {c['per_class']} per class across {', '.join(c['classes'])}; required macro F1 >=0.70.")
    lines+=['','Sign is constant within each challenge. This removes sign as a within-subset predictor, but does not eliminate all possible source/style confounds. HOLDOUT was excluded from baseline scoring and challenge construction.',
        '', '## Tokenizer and views','',
        'Pinned Auditor tokenizer only: `unsloth/Phi-3.5-mini-instruct-bnb-4bit`, revision `5c20803aa197416f43fb455e55c85178775320cb`. The exact frozen prompt, V2 clarification, chat template and reference canonicalizer were used. Asset hashes are verified without weight access.',
        '', 'Prompt tokens: '+json.dumps(t,sort_keys=True)+'.',
        '', f"Merged four-way TRAIN: 192 unchanged historical substantive rows + {e['train']['external']} external TRAIN = {e['train']['total']}. No historical refusal, DEV or V1 row is included. The original historical refusal mechanism remains separate. All V1 release bytes and historical evidence remain unchanged; V1 admission stays false.",
        '', '## Next experiment and projection','',
        '`AUDITOR_EXTERNAL_RELATION_CLASSIFIER_V2` is prepared but not executed or admitted: frozen historical refusal veto -> same frozen checkpoint-120 representation and four-way linear classifier -> conditioned explanation. The first measurement is classification only; no explanation or veto generation is included. Use final prompt-token hidden states (3072 dimensions), TRAIN-only standardization, 12,292 head parameters, 200 Adam updates, seed 7, lr 0.01 and prior 0.001 weight regularization. No classifier-specific LoRA is authorized.',
        '', f"Primary external DEV: {e['dev']['external']} rows. Historical substantive canonical DEV: 48 rows, secondary distribution-shift diagnostic. External gates remain macro F1 >=0.75, every class recall >=0.60; each challenge requires macro F1 >=0.70. Aspirational overall gates are 0.80/0.70. HOLDOUT is excluded and requires separate authorization. Historical integrated gates remain recorded.",
        '', f"Projection only: feature extraction {p['feature_seconds']:.2f}s total (TRAIN {p['train_feature_seconds']:.2f}s; external DEV {p['external_dev_feature_seconds']:.2f}s; historical DEV {p['historical_dev_feature_seconds']:.2f}s). Head training approximately {p['head_seconds']:.2f}s, scaling historical measurements. Expected peak GPU allocation 3.56-4.5 GiB. Setup-inclusive planning range: 15-30 A10 minutes / $0.3225-$0.645 using the historical $1.29/hour rate. This is not a current price quote, a hard bound, or cloud authorization. Explanation generation is excluded.",
        '', '## Validation and verdict','',
        'Checks cover source/archive hashes, official split footer counts/schema, atomic reconstruction, label/orientation preservation, provenance round-trip, symmetric duplicates, exact/near lineage containment, common ratio bins, four-class/sign balance, challenge construction, tokenizer ceiling, metadata exclusion, unchanged historical rows and V1 quarantine. Unit tests compare the prefix index against exhaustive lexical similarity and prove rejection of invalid alignment, placeholders, identity pairs, tampering, unauthorized data access and prohibited runtime operations. Reversed input ordering and independent-process artifact rebuild evidence are retained.',
        '', 'HOLDOUT receipt remains consumed=false. No HOLDOUT prediction/evaluation was run. Public data/documentation/license downloads only; no new LLM labels, model inference/generation, model weights, training, cloud compute, paid API, Producer execution, protected access, or push.',
        '', '`AUDITOR_EXTERNAL_RELATION_DATA_V2_NOT_READY`']
    (ROOT/'docs/fix/AUDITOR_EXTERNAL_RELATION_DATA_V2.md').write_bytes(('\n'.join(lines)+'\n').encode())

if __name__=='__main__':main()
