"""Authored fixtures only; no semantic outputs are generated by these checks."""
import argparse
import ast
from copy import deepcopy
import json
from pathlib import Path
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import patch

import agent_briefs
import run_options as options
import strategic_support as strategy
import multi_round as mr
from run_context import for_run_dir

ROOT = Path(__file__).resolve().parent.parent


def fixture():
    return json.loads((ROOT / "benchmark/fixtures/brief_language_strategy.json").read_text(encoding="utf-8"))


def record(language="tr", mode="recommendation"):
    from reference_builder import ReferenceIndex
    from multi_round_phase import accept_review
    f = fixture()["turkish_case"]
    with tempfile.TemporaryDirectory() as directory:
        ctx = for_run_dir(ROOT, Path(directory))
        refs = ReferenceIndex.open(ROOT, index_path=ctx.reference_index_path())
        manifest = deepcopy(f["manifest"])
        manifest.update(decision_support_mode=mode, allow_recommendations=mode == "recommendation")
        r = mr.begin(ctx, manifest)
        r["evidence"] = mr.bind_sources(manifest, f["documents"], refs)
        producer = dict(agent="PROCESSOR", backend="fixture_producer", model="authored_p", call_id="call_p")
        reviewer = dict(agent="VERIFIER", backend="fixture_auditor", model="authored_v", call_id="call_v")
        r["records"] = accept_review(manifest, r["evidence"], f["producer_envelope"]["items"],
                                    f["reviewer_envelope"]["items"], producer=producer, verifier=reviewer)
        proposals = deepcopy(fixture()["strategies"][language])
        if mode == "strategic_options":
            proposals = [p for p in proposals if p["type"] == "STRATEGIC_OPTION"]
        if mode in {"trajectory_only", "decision_support"}:
            r["strategic_layer"] = strategy.empty(r)
        else:
            decisions = [dict(target_record_id=p["record_id"], state="accepted", confidence="UNCERTAIN", source_ids=p["source_ids"]) for p in proposals]
            r["strategic_layer"] = strategy.reviewed(r, proposals, decisions, producer, reviewer)
        return r


class BriefChecks(unittest.TestCase):
    def test_current_rules_and_draft_references_are_dynamic(self):
        from bus_reader import assemble_context
        w = self.wrapper(language="tr")
        pkg = assemble_context(w.backend, w.constitution, w.bus, {"document_id": "doc1"},
                               convention_registry={"conventions": [{"id": "CONV-1", "rule": "fixture rule", "category": "fixture"}]})
        self.assertNotIn("CONVENTION_REGISTRY", pkg.stable_text())
        self.assertIn("CONVENTION_REGISTRY", pkg.dynamic_text())
        source = ast.parse((ROOT / "scripts/pipeline.py").read_text(encoding="utf-8"))
        function = next(n for n in source.body if isinstance(n, ast.FunctionDef) and n.name == "build_draft_prompt")
        scope = {"DRAFT_SYSTEM_PROMPT": "stable task"}
        exec(compile(ast.Module(body=[function], type_ignores=[]), "draft_prompt", "exec"), scope)
        stable, dynamic = scope[function.name]("fixture question", [{"ref_id": "REF-0001", "text": "current source"}])
        self.assertEqual(stable, "stable task")
        self.assertIn("REF-0001", dynamic)
        self.assertIn("current source", dynamic)
        direct = options.direct_prefix(w, stable, w.run_context)
        self.assertIn("Turkish", direct)
        self.assertIn("free-text memo", direct)

    def wrapper(self, name="PROCESSOR", language="en", enabled="enabled"):
        from agent_wrapper import AgentWrapper
        from constitution import Constitution
        from message_bus import MessageBus
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        ctx = for_run_dir(ROOT, Path(temporary.name))
        options.configure(ctx, "auto", language, enabled)
        registry = json.loads((ROOT / "config/agent_registry.json").read_text(encoding="utf-8"))["agents"]
        contracts = json.loads((ROOT / "config/agent_contracts.json").read_text(encoding="utf-8"))["contracts"]
        return AgentWrapper(name, Constitution.load(ROOT / "config/constitution.json"), MessageBus.open(ctx.bus_path()),
                            registry, contracts, keys={"fixture_only": True}, run_context=ctx)

    def test_all_active_briefs_match_registry_contract_and_interfaces(self):
        registry = json.loads((ROOT / "config/agent_registry.json").read_text(encoding="utf-8"))["agents"]
        contracts = json.loads((ROOT / "config/agent_contracts.json").read_text(encoding="utf-8"))["contracts"]
        self.assertEqual(set(registry), set(agent_briefs.INTERFACES))
        import agent_activation
        for name, spec in registry.items():
            b = agent_briefs.brief(name, spec, contracts[name])
            self.assertEqual(b["responsibility"], spec["does"])
            self.assertEqual(b["excluded"], spec["does_not"])
            self.assertEqual(b["output_required"], contracts[name]["required"])
            self.assertEqual(b["consumer_contract"], agent_activation._PURPOSES.get(name, "advisory_board_and_deliverable"))
            self.assertTrue(b["upstream"] and b["downstream"])
        pipeline = (ROOT / "scripts/pipeline.py").read_text(encoding="utf-8")
        ranks = next(n.value for n in ast.parse(pipeline).body if isinstance(n, ast.Assign)
                     and any(isinstance(t, ast.Name) and t.id == "_EDITORIAL_RANKS" for t in n.targets))
        self.assertEqual(tuple(ast.literal_eval(ranks)), agent_briefs._RANKS)
        self.assertIn("_deepen_legal_analyst_findings_local", pipeline)
        self.assertIn("LEGAL_ANALYST", agent_briefs.INTERFACES["AMENDMENT_DRAFTER"][0])
        self.assertIn("conditional EDITOR_HEAD_OF_UNIT", agent_briefs.INTERFACES["EDITOR_CLERK"][2])

    def test_no_conclusion_trust_or_new_routing(self):
        w = self.wrapper()
        text = agent_briefs.render(w.name, w.spec, w.contract)
        self.assertIn("Check evidence independently", text)
        self.assertIn("do not imply their availability", text)
        self.assertIn("merely because of their author", text)
        self.assertNotIn("assume", text.lower())
        self.assertEqual(w.spec["model"], w.model)

    def test_static_dynamic_separation_and_disable_effect(self):
        w = self.wrapper()
        pkg = SimpleNamespace(stable_text=lambda: "fixed governance", dynamic_sections=lambda: [("RECENT_BUS", "current evidence"), ("WORK_PAYLOAD", "duplicated marker")])
        stable, dynamic = w.build_prompt(pkg, {"document_id": "doc1"})
        stable2, dynamic2 = w.build_prompt(pkg, {"document_id": "doc2"})
        self.assertEqual(stable, stable2)
        self.assertNotEqual(dynamic, dynamic2)
        self.assertNotIn("current evidence", stable)
        self.assertNotIn("duplicated marker", dynamic)
        self.assertIn("Agent execution brief", stable)
        self.assertIn("fixed governance", stable)
        options.configure(w.run_context, agent_briefs="disabled")
        without, _ = w.build_prompt(pkg, {"document_id": "doc1"})
        self.assertNotIn("Agent execution brief", without)
        self.assertLess(len(without), len(stable))

    def test_reference_and_dag_prompts_and_prefix_metadata(self):
        import execution_topology as topology
        from execution_scheduler import Lane
        from agent_wrapper import CallResult
        for dag in [False, True]:
            w = self.wrapper(language="tr")
            captured = []
            def dispatch(stable, dynamic, **kwargs):
                captured.append((stable, dynamic))
                return CallResult(w.backend, w.model, json.dumps({"agent": w.name, "doc_id": "doc1", "items": []}))
            w.dispatch = dispatch
            runtime = topology.Runtime([Lane("fake")]) if dag else None
            try:
                if runtime:
                    runtime.attach(w)
                result = w.run_task(work_payload={"document_id": "doc1", "text": fixture()["language_cases"][0]["text"]}, max_tokens=64)
                self.assertTrue(result["ok"])
                self.assertIn("Turkish", captured[0][0])
                rows = [json.loads(line) for line in (w.run_context.logs_dir() / "prompt_structure.jsonl").read_text().splitlines()]
                self.assertEqual(rows[0]["call_id"], result["call_id"])
                self.assertEqual(rows[0]["output_language"], "tr")
                self.assertNotIn("text", rows[0])
                self.assertIsNone(rows[0]["cache_hit"])
            finally:
                if runtime:
                    runtime.close()

    def test_neutralise_brief_insertion_fail_restore(self):
        w = self.wrapper()
        pkg = SimpleNamespace(stable_text=lambda: "", dynamic_sections=lambda: [])
        def oracle():
            self.assertIn("Agent execution brief", w.build_prompt(pkg, {})[0])
        oracle()
        with patch.object(agent_briefs, "render", lambda *a: ""):
            with self.assertRaises(AssertionError):
                oracle()
        oracle()


class LanguageChecks(unittest.TestCase):
    def test_actual_api_validation_and_worker_argument_projection(self):
        tree = ast.parse((ROOT / "scripts/server.py").read_text(encoding="utf-8"))
        submit = next(n for n in tree.body if isinstance(n, ast.AsyncFunctionDef) and n.name == "submit")
        validation = next(n for n in submit.body if isinstance(n, ast.Try) and "run_options.normalize(input_language" in ast.unparse(n))
        class HTTPRefusal(Exception):
            pass
        for language in ["en", "tr", "auto", "", None]:
            scope = dict(run_options=options, input_language="auto", output_language=language, agent_briefs=None, HTTPException=HTTPRefusal)
            if language in {"auto", ""}:
                with self.assertRaises(HTTPRefusal):
                    exec(compile(ast.Module(body=[validation], type_ignores=[]), "server_language_validation", "exec"), scope)
            else:
                exec(compile(ast.Module(body=[validation], type_ignores=[]), "server_language_validation", "exec"), scope)
                worker = next(n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == "_run_job")
                projection = next(n for n in ast.walk(worker) if isinstance(n, ast.AugAssign) and
                                  isinstance(n.target, ast.Name) and n.target.id == "argv" and "--input-language" in ast.unparse(n))
                scope["argv"] = []
                exec(compile(ast.Module(body=[projection], type_ignores=[]), "server_language_argv", "exec"), scope)
                self.assertEqual(scope["argv"][3], language or "en")

    def test_defaults_auto_and_invalid_configuration(self):
        self.assertEqual(options.normalize(), options.Options())
        self.assertIn("without a forced language classification", options.instruction(options.Options()))
        for kwargs in ({"input_language": "xx"}, {"output_language": "auto"}, {"output_language": ""}, {"agent_briefs": "yes"}):
            with self.assertRaises(ValueError):
                options.normalize(**kwargs)

    def test_cross_language_and_mixed_input_authored_outputs(self):
        for case in fixture()["language_cases"]:
            language = options.normalize(case["input_language"], case["output_language"])
            self.assertIn({"en": "English", "tr": "Turkish"}[case["output_language"]], options.instruction(language))
            data = {"ref": "REF-0001", "rule_id": "CONV-1", "movement": "concession", "value": 3.5,
                    "text": case["text"], "explanation": case["explanation"]}
            self.assertEqual(json.loads(json.dumps(data, ensure_ascii=False)), data)

    def test_turkish_review_evidence_citations_and_contract_stability(self):
        from amendment_render import render_amendments_md, _md_amendment_count
        payload = fixture()["ordinary_tr"]
        before = deepcopy(payload)
        text = render_amendments_md(payload, output_language="tr")
        self.assertIn("İnceleme", text)
        self.assertIn("Kaynaklar", text)
        for field in ("comment", "original_text"):
            self.assertIn(payload["amendments"][0][field], text)
        self.assertIn("REF-0001", text)
        self.assertIn("CONV-1", text)
        self.assertIn("3.5", text)
        self.assertEqual(_md_amendment_count(text), 1)
        self.assertEqual(payload, before)

    def test_saved_options_and_invalid_saved_refusal(self):
        with tempfile.TemporaryDirectory() as directory:
            ctx = for_run_dir(ROOT, Path(directory))
            self.assertEqual(options.saved(directory).output_language, "en")
            options.configure(ctx, "auto", "tr")
            self.assertEqual(options.saved(directory).output_language, "tr")
            (ctx.audit_dir() / "run_options.json").write_text('{"schema_version": 1, "output_language": "xx"}')
            with self.assertRaises(ValueError):
                options.saved(directory)

    def test_api_ui_cli_agreement_without_service_start(self):
        server = ast.parse((ROOT / "scripts/server.py").read_text(encoding="utf-8"))
        submit = next(n for n in server.body if isinstance(n, ast.AsyncFunctionDef) and n.name == "submit")
        self.assertTrue({"input_language", "output_language", "agent_briefs"}.issubset({a.arg for a in submit.args.args}))
        self.assertIn("run_options.normalize(input_language, output_language, agent_briefs)", ast.unparse(submit))
        worker = next(n for n in server.body if isinstance(n, ast.FunctionDef) and n.name == "_run_job")
        self.assertIn("'--output-language', language.output_language", ast.unparse(worker))
        ui = (ROOT / "scripts/ui/console.html").read_text(encoding="utf-8")
        self.assertIn('id="s-language"', ui)
        self.assertIn("fd.append('output_language', outputLanguage)", ui)
        self.assertIn("escapeHtml(displayValue(node.type, node.display_label))", ui)
        import agent_activation
        tree = ast.parse((ROOT / "scripts/pipeline.py").read_text(encoding="utf-8"))
        node = next(n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == "_build_arg_parser")
        scope = dict(argparse=argparse, agent_activation=agent_activation)
        exec(compile(ast.Module(body=[node], type_ignores=[]), "parser", "exec"), scope)
        args = scope[node.name]().parse_args(["--output-language", "tr"])
        self.assertEqual(args.output_language, "tr")
        self.assertFalse(args.multi_round)
        self.assertEqual(args.execution_topology, "reference_serial")


class StrategyChecks(unittest.TestCase):
    def test_actual_console_renderer_with_bilingual_api_fixtures(self):
        import subprocess
        import shutil
        if shutil.which("node") is None:
            self.skipTest("Node unavailable for offline UI execution")
        values = []
        for language in ("en", "tr"):
            r = record(language)
            r["strategic_layer"]["items"][0]["action"] = "<script>bad()</script>"
            values.append(dict(recorded=True, fixture=True, activation={"state": "fixture"}, run_id="fixture",
                               view=mr.project(r), strategic_support=strategy.project(r, language)))
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "ui.json"
            path.write_text(json.dumps(values, ensure_ascii=False), encoding="utf-8")
            result = subprocess.run(["node", str(ROOT / "scripts/ui/brief_language_strategy_checks.js"), str(path)],
                                    capture_output=True, text=True, timeout=15)
            self.assertEqual(result.returncode, 0, result.stderr)

    def test_single_option_and_rejected_option_withholds_recommendation(self):
        r = record()
        proposals = fixture()["strategies"]["en"]
        producer = dict(agent="PROCESSOR", backend="p", model="p", call_id="p")
        reviewer = dict(agent="VERIFIER", backend="v", model="v", call_id="v")
        decisions = [dict(target_record_id=p["record_id"], state="rejected" if p["record_id"] == "option_1" else "accepted",
                          confidence="UNCERTAIN", source_ids=p["source_ids"]) for p in proposals]
        layer = strategy.reviewed(r, proposals, decisions, producer, reviewer)
        self.assertEqual(layer["items"][-1]["state"], "unresolved")
        self.assertEqual(layer["state"], "strategic_options")
        self.assertEqual(len(layer["items"]), 3)
        r["manifest"]["decision_support_mode"] = "strategic_options"
        one = strategy.reviewed(r, proposals[1:2], decisions[1:2], producer, reviewer)
        self.assertEqual(len(one["items"]), 1)

    def test_saved_api_keeps_trajectory_if_strategy_corrupt(self):
        from multi_round_checks import saved
        with tempfile.TemporaryDirectory() as directory:
            ctx = for_run_dir(ROOT, Path(directory))
            r = saved(ctx)
            options.configure(ctx, output_language="tr")
            r["manifest"].update(decision_support_mode="recommendation", allow_recommendations=True)
            # Same identities and contracts, authored strategy attached to the saved source graph.
            r["strategic_layer"] = record()["strategic_layer"]
            mr.write_record(ctx, r)
            read = mr.read_saved(ctx.run_dir, ctx.run_id)
            self.assertTrue(read["recorded"])
            self.assertEqual(read["strategic_support"]["output_language"], "tr")
            r["strategic_layer"]["items"][0]["trajectory_ids"] = ["missing"]
            mr.write_record(ctx, r)
            read = mr.read_saved(ctx.run_dir, ctx.run_id)
            self.assertTrue(read["recorded"])
            self.assertEqual(read["view"], mr.project(r))
            self.assertEqual(read["strategic_support"]["state"], "recommendation_unavailable")

    def test_layers_are_distinct_and_quotes_never_advice(self):
        r = record()
        view = strategy.project(r, "tr")
        self.assertEqual({n["type"] for n in view["layers"]}, strategy.TYPES)
        observed = [n for n in view["layers"] if n["type"] == "OBSERVED"]
        self.assertEqual([n["text"] for n in observed], [s["quote"] for s in r["evidence"]])
        self.assertTrue(all(n["display_label"] == "Gözlemlenen kanıt" for n in observed))
        self.assertEqual(len([n for n in view["layers"] if n["type"] == "STRATEGIC_OPTION"]), 2)

    def test_provenance_identity_missing_links_and_uncertainty_refuse(self):
        good = record()
        for field, value in [("source_ids", []), ("trajectory_ids", ["missing"]), ("actor_ids", ["actor_b"]),
                             ("round_ids", ["r2"]), ("confidence", "CONFIDENT"), ("type", "OBSERVED")]:
            r = deepcopy(good)
            r["strategic_layer"]["items"][0][field] = value
            with self.assertRaises(mr.InvalidState):
                strategy.project(r)
        r = deepcopy(good)
        r["strategic_layer"]["items"][-1]["option_ids"] = []
        with self.assertRaises(mr.InvalidState):
            strategy.project(r)

    def test_explicit_modes_do_not_activate_recommendation(self):
        for selected in ("trajectory_only", "decision_support", "strategic_options"):
            r = record(mode=selected)
            self.assertFalse(any(n["type"] == "RECOMMENDATION" for n in strategy.project(r)["layers"]))
        with self.assertRaises(mr.InvalidState):
            strategy.mode({"decision_support_mode": "recommendation"})

    def test_insufficient_evidence_does_not_fabricate_strategy(self):
        r = record()
        original = deepcopy(r["records"])
        r["strategic_layer"] = strategy.empty(r, "insufficient_evidence")
        self.assertEqual(strategy.project(r)["state"], "insufficient_evidence")
        self.assertEqual(r["records"], original)
        self.assertFalse(any(n["type"] == "RECOMMENDATION" for n in strategy.project(r)["layers"]))

    def test_competing_options_language_and_machine_schema_stability(self):
        for language in ("en", "tr"):
            r = record(language)
            before = deepcopy(r)
            view = strategy.project(r, language)
            rendered = strategy.render_html(view)
            self.assertIn(options.label("STRATEGIC_OPTION", language), rendered)
            self.assertEqual(r, before)
            proposals = [n for n in view["layers"] if n["type"] == "STRATEGIC_OPTION"]
            self.assertEqual(len(proposals), 2)
            self.assertTrue(all(p["confidence"] == "UNCERTAIN" and p["assumptions"] for p in proposals))
            self.assertEqual([p["record_id"] for p in proposals], ["option_1", "option_2"])

    def test_renderer_escapes_authored_content(self):
        r = record()
        r["strategic_layer"]["items"][0]["action"] = "<script>bad()</script>"
        rendered = strategy.render_html(strategy.project(r))
        self.assertNotIn("<script>", rendered)
        self.assertIn("&lt;script&gt;", rendered)

    def test_unreviewed_strategy_not_publishable(self):
        r = record()
        r["strategic_layer"]["reviewed"] = False
        with self.assertRaises(mr.InvalidState):
            strategy.project(r)

    def test_neutralise_provenance_fail_restore(self):
        r = record()
        r["strategic_layer"]["items"][0]["source_ids"] = []
        def oracle():
            with self.assertRaises(mr.InvalidState):
                strategy.project(r)
        oracle()
        with patch.object(strategy, "validate", lambda r, layer: layer):
            with self.assertRaises(AssertionError):
                oracle()
        oracle()

    def test_optional_execution_with_authored_wrappers_and_failure_isolation(self):
        r = record()
        proposals = fixture()["strategies"]["en"]
        calls = []
        def factory(name):
            return SimpleNamespace(name=name, backend=name, model=name)
        def call(wrapper, contract, payload, case_id, objectives):
            calls.append(wrapper.name)
            items = proposals if wrapper.name == "PROCESSOR" else [dict(target_record_id=p["record_id"], source_ids=p["source_ids"], state="accepted", confidence="UNCERTAIN") for p in proposals]
            return dict(agent=wrapper.name, backend=wrapper.backend, model=wrapper.model, call_id="authored_" + wrapper.name, values=items)
        layer = strategy.execute(r, {"PROCESSOR": {}, "VERIFIER": {}}, factory, call, lambda reply, *a: reply["values"], "")
        self.assertEqual(calls, ["PROCESSOR", "VERIFIER"])
        self.assertEqual(len(layer["items"]), 3)
        old = deepcopy(r["records"])
        unavailable = strategy.execute(r, {}, factory, call, lambda *a: [], "")
        self.assertEqual(unavailable["state"], "recommendation_unavailable")
        self.assertEqual(r["records"], old)
        r["manifest"]["decision_support_mode"] = "trajectory_only"
        strategy.execute(r, {}, lambda *a: self.fail("unrequested call"), call, lambda *a: [], "")


if __name__ == "__main__":
    unittest.main()
