"""Snapshot / restore / reset (operator spec item 1).

Protected durable learnings/caches live under durable/ (INFRA-030); a domain
snapshot bundles the resettable slice of that plus a few config files:
  config/constitution.json         (with all accumulated legislation)
  config/convention_registry.json
  config/review_scope.json
  prompts/project_rules.md
  durable/cache/      (embedding store, verification cache tier-2)
  durable/learnings/  (institutions, citations, speech-acts, search learnings,
                       discovered APIs, document dates)
  durable/reference/  (LINGUISTIC_IDENTITY.md, situational_awareness.md)
A snapshot deliberately EXCLUDES durable/global (tier-3 cross-project cache) and
durable/governance (operator-approval + amendment-guard ledgers).

reset_snapshot() is SNAPSHOT-FIRST and GOVERNANCE-PRESERVING (INFRA-029/030):
  - backs up everything to a snapshot BEFORE stripping anything;
  - strips resettable DOMAIN LEARNING by location: durable/{cache,learnings,reference};
  - NEVER touches durable/global, durable/governance, or config/constitution.json
    (governance history survives) — protection is structural, by location;
  - deletes regenerable config (convention_registry, review_scope), resets
    prompts/project_rules.md, clears per-run output/, empties input/operational/;
  - input/context/ and input/conventions/ preserved (operator-supplied inputs).
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

from constitution_guard import check_constitution_change
import durable_paths


# A domain snapshot travels with: a few config files (constitution + the compiled
# convention registry + review scope), the project_rules prompt, and the
# RESETTABLE durable subdirs (cache, learnings, reference). It deliberately does
# NOT include durable/global (cross-project tier-3 cache) or durable/governance
# (operator-approval + amendment-guard ledgers). The protected learnings/caches
# now live under durable/ (INFRA-030), so they are snapshotted by copying those
# durable subdirs, not by enumerating config/reference files.
_SNAPSHOT_CONFIG = ["constitution.json", "convention_registry.json", "review_scope.json"]
_SNAPSHOT_PROMPTS = ["project_rules.md"]
_SNAPSHOT_DURABLE_SUBDIRS = list(durable_paths.RESETTABLE_SUBDIRS)  # cache, learnings, reference


_GENESIS_CONSTITUTION = {
    "version": "1.0.0",
    "description": "Reset to genesis defaults (7 seed laws only).",
    "seed_laws": [
        {"id": "LAW-0", "title": "Operator sovereignty", "priority": 0, "immutable": True,
         "text": "The operator is the sole source of constitutional authority. No agent, task force, supervisor, or orchestrator may create, amend, or repeal a law without operator approval. The constitution governs all agent behavior. Silence in the constitution means escalate — never assume permission. Every operator decision on an escalation is recorded as legislation (precedent, task force law, or amendment) for future runs.",
         "outranked_by": ["LAW-IV"]},
        {"id": "LAW-I", "title": "Do no harm to the source", "priority": 1, "immutable": True,
         "text": "No agent may alter, fabricate, or suppress information from source documents. An agent may flag, annotate, footnote, and warn — but the source record is sacred. When source content conflicts with external evidence, both are preserved and the operator decides. No agent may resolve a factual conflict by choosing one version over another."},
        {"id": "LAW-II", "title": "Know your bounds", "priority": 2, "immutable": True,
         "text": "Each agent has a fixed capability set defined in the agent registry. An agent may request another agent's service but may not perform another agent's function. An agent that detects itself reasoning outside its defined scope must stop and yield to the appropriate agent. The capability boundary is the agent's identity — crossing it is not initiative, it is malfunction."},
        {"id": "LAW-III", "title": "No self-audit", "priority": 3, "immutable": True,
         "text": "No model may verify, fact-check, or audit output that was generated by the same model family. Claude-generated content is audited by GPT or local models. GPT-generated content is audited by Claude or local models. Local model output is audited by cloud models. The audit trail must show which model produced and which model verified every output segment."},
        {"id": "LAW-IV", "title": "Protect what is private", "priority": 4, "immutable": True,
         "text": "Sensitive content — PII, classified material, institutional secrets, content marked for redaction — must be processed exclusively by offline agents running on local hardware. No sensitive content may traverse a network, enter an API call, or leave the operator's machine. This law cannot be overridden by any subsequent legislation, precedent, amendment, or operator instruction. It outranks LAW-0 for this specific scope. A single leak is irreversible.",
         "outranks": ["LAW-0"]},
        {"id": "LAW-V", "title": "Remember before you act", "priority": 5, "immutable": True,
         "text": "Before executing any search, verification, or computation, an agent must check in order: (a) the constitution for governing law, (b) the precedent registry for prior rulings, (c) the verification memory for cached results, (d) the run objectives for alignment. Act on the first match found. Only when all four are silent may the agent proceed with a novel action — and that action's outcome must be recorded for future consultation.",
         "check_order": ["constitution", "precedents", "verification_cache", "run_objectives"]},
        {"id": "LAW-VI", "title": "Structure is earned, not assumed", "priority": 6, "immutable": True,
         "text": "All organizational structure below the Top Orchestrator emerges from identified work. Agents form task forces by drafting charters. Charters require constitutional approval from the Top Orchestrator, which checks against existing legislation. If the constitution is silent on the proposed pattern, the Top Orchestrator escalates to the operator. Approved charters become task force laws upon dissolution. No structure persists beyond its purpose — a task force with no remaining work must dissolve. No agent may invent work to justify its existence."},
    ],
    "task_force_laws": [], "precedents": [], "amendments": [],
}


_CLEAN_PROJECT_RULES = (
    "# Project rules\n\n"
    "This file holds project-specific rules layered over the constitution. The seed laws "
    "(LAW-0 through LAW-VI in `config/constitution.json`) outrank everything written here. "
    "These rules are domain-agnostic placeholders; operator-approved, project-scoped "
    "DELTAs are recorded in the DELTAs section below. (adaptive_spawn's per-run "
    "statistics are runtime telemetry and are NOT written to this tracked file — they "
    "go to the durable runtime log `durable/learnings/spawn_log.jsonl`.)\n\n"
    "## Manual rules (operator-set)\n\n"
    "_(None yet. Add rules here that should apply to every run of this project. "
    "Use the same prose voice as the seed laws — short, declarative, no ambiguity. "
    "Each rule should cite the operator decision or DELTA that produced it.)_\n\n"
    "## DELTAs flushed by adaptive spawn\n\n"
    "_(Populated automatically when the audit synthesis proposes a project-scoped DELTA "
    "and the operator approves. Do not edit by hand. This records operator-approved "
    "project DELTAs, not raw per-run spawn statistics.)_\n"
)


def _now(): return datetime.now(timezone.utc).isoformat()


def list_snapshots(project_root: Path) -> list[dict]:
    base = project_root / "snapshots"
    if not base.exists():
        return []
    out = []
    for sub in sorted(base.iterdir()):
        if not sub.is_dir():
            continue
        meta_path = sub / "_snapshot.json"
        meta = {}
        if meta_path.exists():
            try: meta = json.loads(meta_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError: meta = {}
        out.append({"name": sub.name, "path": str(sub), **meta})
    return out


def _clear_run_output(project_root: Path) -> bool:
    """Delete every per-run folder under output/runs/ (disposable; INFRA-032),
    preserving the .gitkeep placeholder. Confined to output/runs/ by construction
    — it never touches durable/ or config/. Returns True if anything was removed."""
    runs_dir = project_root / "output" / "runs"
    if not runs_dir.is_dir():
        return False
    removed = False
    for f in runs_dir.glob("*"):
        if f.name == ".gitkeep":
            continue
        if f.is_dir():
            shutil.rmtree(f)
        else:
            f.unlink()
        removed = True
    return removed


def save_snapshot(project_root: Path, name: str, *, overwrite: bool = False) -> Path:
    target = project_root / "snapshots" / name
    if target.exists() and not overwrite:
        raise FileExistsError(f"snapshot {name!r} already exists; pass overwrite=True to replace")
    if target.exists():
        shutil.rmtree(target)
    (target / "config").mkdir(parents=True, exist_ok=True)
    (target / "prompts").mkdir(parents=True, exist_ok=True)
    (target / "durable").mkdir(parents=True, exist_ok=True)
    copied = []
    for fn in _SNAPSHOT_CONFIG:
        src = project_root / "config" / fn
        if src.exists():
            shutil.copy2(src, target / "config" / fn); copied.append(f"config/{fn}")
    for fn in _SNAPSHOT_PROMPTS:
        src = project_root / "prompts" / fn
        if src.exists():
            shutil.copy2(src, target / "prompts" / fn); copied.append(f"prompts/{fn}")
    # Resettable durable subdirs (cache, learnings, reference) copied wholesale.
    for sub in _SNAPSHOT_DURABLE_SUBDIRS:
        src = durable_paths.durable_root(project_root) / sub
        if src.is_dir():
            shutil.copytree(src, target / "durable" / sub, dirs_exist_ok=True)
            copied.append(f"durable/{sub}/")
    meta = {"name": name, "saved_at": _now(), "files": copied}
    (target / "_snapshot.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False),
                                            encoding="utf-8")
    return target


def load_snapshot(project_root: Path, name: str, *,
                  operator_handler=None, interactive: bool = False) -> dict:
    target = project_root / "snapshots" / name
    if not target.is_dir():
        raise FileNotFoundError(f"snapshot {name!r} not found")
    summary = {"name": name, "restored": [], "cleared": [], "preserved": [], "skipped": []}
    for fn in _SNAPSHOT_CONFIG:
        src = target / "config" / fn
        if not src.exists():
            continue
        dst = project_root / "config" / fn
        if fn == "constitution.json":
            # Amendment tripwire (INFRA-029): restoring a snapshot's constitution
            # must not silently modify/delete existing live amendments or seed
            # laws. If it would, require operator approval; without it, PRESERVE
            # the live constitution (skip the restore) rather than clobber.
            try:
                proposed = json.loads(src.read_text(encoding="utf-8"))
            except Exception:
                proposed = {}
            verdict = check_constitution_change(
                dst, proposed, operator_handler=operator_handler,
                interactive=interactive, reason=f"load_snapshot:{name}",
                project_root=project_root,
            )
            if not verdict["allowed"] and verdict["violations"]:
                summary["skipped"].append(
                    f"config/constitution.json (live governance preserved; "
                    f"{len(verdict['violations'])} protected change(s) need operator approval)")
                continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst); summary["restored"].append(f"config/{fn}")
    for fn in _SNAPSHOT_PROMPTS:
        src = target / "prompts" / fn
        if src.exists():
            dst = project_root / "prompts" / fn
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst); summary["restored"].append(f"prompts/{fn}")
    # Restore the resettable durable subdirs (cache, learnings, reference) from
    # the snapshot, replacing the live ones. durable/global and durable/governance
    # are NOT in the snapshot and are therefore preserved untouched (INFRA-030).
    for sub in _SNAPSHOT_DURABLE_SUBDIRS:
        snap = target / "durable" / sub
        if not snap.is_dir():
            continue
        live = durable_paths.durable_root(project_root) / sub
        if live.exists():
            shutil.rmtree(live)
        shutil.copytree(snap, live)
        summary["restored"].append(f"durable/{sub}/")
    # Clear disposable per-run output (output/runs/*; INFRA-032). Governance
    # ledgers live in durable/governance, outside output/, so nothing protected
    # is touched here.
    if _clear_run_output(project_root):
        summary["cleared"].append("output/runs/* (per-run artifacts)")
    return summary


def reset_snapshot(project_root: Path) -> dict:
    """Strip resettable DOMAIN LEARNING toward genesis defaults — SNAPSHOT-FIRST
    and GOVERNANCE-PRESERVING (INFRA-029 / genesis Part XXVII §B). Two tiers:

      - domain learning (discovered institutions / citations / speech-acts /
        search-strategy learnings / per-domain caches, embeddings, reference
        assets, project_rules) is resettable — but ONLY after an automatic
        backup snapshot is written first (never strip-without-backup);
      - GOVERNANCE HISTORY is NEVER deleted: config/constitution.json (its
        amendments[]/precedents/task-force laws) is left untouched, and the
        operator-approval / amendment-guard ledgers under durable/governance
        survive (INFRA-030). Disposable per-run output (output/runs/*) is cleared.
    """
    summary = {"deleted": [], "reset": [], "preserved": [], "backup": None}

    # (a) SNAPSHOT-FIRST: back up the full learnable state before stripping.
    backup_name = "pre_reset_" + datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    try:
        target = save_snapshot(project_root, backup_name, overwrite=True)
        summary["backup"] = str(target)
    except Exception as e:
        # Never strip without a backup. If the backup fails, abort the reset.
        summary["error"] = f"backup failed, reset aborted: {type(e).__name__}: {e}"
        return summary

    # (b) Strip resettable DOMAIN LEARNING by LOCATION: only the resettable
    #     durable subdirs (cache, learnings, reference). durable/global and
    #     durable/governance are NEVER iterated here, so protection is structural
    #     (INFRA-030), not a name-check. config/constitution.json is untouched.
    for sub in durable_paths.RESETTABLE_SUBDIRS:
        d = durable_paths.durable_root(project_root) / sub
        if d.is_dir():
            for f in d.glob("*"):
                if f.is_file(): f.unlink()
                elif f.is_dir(): shutil.rmtree(f)
            summary["deleted"].append(f"durable/{sub}/*")
    for sub in durable_paths.PRESERVED_SUBDIRS:
        summary["preserved"].append(f"durable/{sub}/* (protected; never touched by reset)")
    summary["preserved"].append("config/constitution.json (governance history)")
    # Delete regenerable / operator config (constitution is NOT in this list).
    for fn in ("convention_registry.json", "review_scope.json"):
        path = project_root / "config" / fn
        if path.exists():
            path.unlink(); summary["deleted"].append(f"config/{fn}")
    # Clear any leftovers in reference/ (learned assets now live in durable/reference).
    ref_dir = project_root / "reference"
    if ref_dir.exists():
        for f in ref_dir.glob("*"):
            if f.is_file(): f.unlink(); summary["deleted"].append(f"reference/{f.name}")
    # Reset prompts/project_rules.md to the clean template.
    rules_path = project_root / "prompts" / "project_rules.md"
    rules_path.parent.mkdir(parents=True, exist_ok=True)
    rules_path.write_text(_CLEAN_PROJECT_RULES, encoding="utf-8")
    summary["reset"].append("prompts/project_rules.md")
    # Clear disposable per-run output (output/runs/*; INFRA-032). Governance
    # ledgers live in durable/governance, outside output/, so nothing protected
    # is touched here.
    if _clear_run_output(project_root):
        summary["deleted"].append("output/runs/* (per-run artifacts)")
    # Empty input/operational/ (runtime artifact per spec).
    op_dir = project_root / "input" / "operational"
    if op_dir.exists():
        for f in op_dir.glob("*"):
            if f.is_file(): f.unlink()
        summary["deleted"].append("input/operational/*")
    return summary
