"""Render the verified linear-probe outcome after cloud cleanup."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1];B=ROOT/'docs/fix/auditor_linear_probe_run'
def read(p):return json.loads(p.read_text(encoding='utf8'))
def table(headers,rows):
    return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(str(v) for v in row)+' |' for row in rows])


def report():
    x=read(B/'RECOMPUTED_RESULTS.json');m=read(B/'manifest.json');t=x['termination'];lines=['# Auditor classification-first linear-probe results','',
        '**'+x['verdict']+'**','',
        'Historical canonical `AUDITOR_TUNING_FAIL` and its adapters/evidence remain unchanged. Historical step120 is still an ineligible standalone Auditor. This run is a separate head-only experiment bound to design commit `25f7dc0cb1bd11d652debbec52940f84e9d64193`.','',
        '## Cloud and cleanup','',
        table(['Item','Value'],[['Tested implementation commit',m['source_commit']],['Provider / region / GPU','Lambda Cloud / '+m['region']+' / A10 24 GB'],['Actual hourly rate',f"${m['hourly_rate']:.2f}"],['Instance',t['instance_id']],['Launch to provider-confirmed termination',f"{t['billable_duration_upper_bound_seconds']:.3f} seconds"],['Estimated cost upper bound',f"${t['estimated_cost_upper_bound_usd']:.6f}"],['Termination UTC',t['utc']],['55-minute limit met',t['billable_duration_upper_bound_seconds']<=3300],['Remaining billable instances','0; provider inventory checked'],['Temporary SSH registration / key','Removed']]),'',
        'Prelaunch projection: 3255 seconds including 300 seconds cleanup; $1.166375 at the confirmed rate. Minute50 cost $1.075; minute55 cost $1.1825. No second instance or fallback. Evidence archive downloaded and hash-verified before termination; long local analysis occurred afterward.','',
        '## Execution and evidence boundaries','',
        'The classifier used citation-normalized original input fields only. Local checks passed alias invariance for all 300 rows and exact refusal-prefix recognition for all 60 saved historical DEV outputs. No saved output was used as a fresh inference lookup. Local feature/autograd and optimizer protocol checks used synthetic stand-ins, not an experimental head or a local backbone run.','',
        'Native features are the final normalized decoder hidden state at the last unpadded prompt token; base/LoRA are frozen. The feature matrix has one stored vector per unique row. Fresh feature identity checks in controls/DEV are separately part of evaluation work. TRAIN-only FP32 population mean/std, clamped at 1e-6, standardize features. W and b alone are optimized.','',
        'Reason generation ends at the first unescaped quote; same-token structural spill is recorded, not treated as reasoning. Full assembled output token count includes the forced prefix, serialized suffix and deterministic native termination. Model throughput counts generated tokens only. Invalid reason or overflow is a failed output; an incomplete run cannot produce a quality PASS/FAIL.','']
    if x['verdict']=='AUDITOR_LINEAR_PROBE_INDETERMINATE':
        lines+=['## Invalidating limitation','',x.get('reason','Incomplete evidence'),'',
                'No complete valid 60-row integrated result is established. Raw-head or final-Auditor success/failure is not inferred from partial evidence. Diagnostic architecture class: not assigned because infrastructure/runtime validity failed.','',
                '```json',json.dumps(x.get('remote_status',{}),indent=2),'```','',
                'Available artifacts: '+', '.join(x.get('available_artifacts',[]))+'.','']
    else:
        p=x['performance'];h=x['head_training'];fm=x['final_auditor'];raw=x['raw_head'];route=x['routing']
        lines+=['## Features and head training','',table(['Measure','Result'],[
            ['Unique features / dimension','300/300 × 3072'],['TRAIN / DEV','240 / 60; 48 / 12 per class'],['Standardization','TRAIN only; no DEV fitting'],['Feature wall',f"{p['feature_seconds']:.6f} s"],['Feature input tokens / second',f"{p['feature_tokens']/p['feature_seconds']:.3f}"],['Trainable parameters','15,365; backbone and LoRA: 0'],['Updates',h['updates']],['Head wall',f"{p['head_seconds']:.6f} s"],['Updates / second',f"{200/p['head_seconds']:.3f}"],['Initial CE',h['initial_ce']],['Final CE after update200',h['final_ce']],['Final regularization contribution',h['final_regularization']],['TRAIN accuracy',h['train_metrics']['accuracy']],['TRAIN macro F1',h['train_metrics']['macro_f1']],['Head SHA-256',x['head_sha256']]]),'',
            'Initial and update200 heads are preserved separately. Only update200 is a candidate. Objective: full-batch softmax CE + 0.001 × mean(W²), Adam FP32 LR0.01, betas0.9/0.999, epsilon1e-8, weight_decay0, seed7, zero W/b, 200 updates, no scheduler or early stopping. Log CE is pre-update; final CE above is recomputed after update200.','',
            '## Raw five-way head DEV','',f"Complete 60/60. Accuracy {raw['accuracy']:.9f}; macro precision {raw['macro_precision']:.9f}; macro recall {raw['macro_recall']:.9f}; macro F1 {raw['macro_f1']:.9f}.",'',
            table(['Expected / predicted',*raw['confusion'].keys()],[[cl,*row.values()] for cl,row in raw['confusion'].items()]),'',
            table(['Class','Precision','Recall','F1','Support'],[[cl,f"{v['precision']:.9f}",f"{v['recall']:.9f}",f"{v['f1']:.9f}",v['support']] for cl,v in raw['per_class'].items()]),'',
            '## Refusal routing','',table(['Measure','Result'],[['Frozen prefix correctness',f"{route['probe_correct']}/60"],['Raw-head refusals',route['raw_head_refusals']],['Frozen-veto refusals',route['veto_refusals']],['Final refusals',route['final_refusals']],['Refusal precision',fm['refusal_precision']],['Refusal recall',fm['refusal_recall']],['Over-refusal',fm['over_refusal_rate']],['Raw versus routed disagreements',', '.join(route['disagreements']) or 'None']]),'',
            '## Explanation and integrated Auditor','',table(['Measure','Result'],[['Generated substantive reasons',p['reasons']],['Fresh integrated DEV','60/60'],['Full DEV wall',f"{p['full_dev_seconds']:.6f} s"],['Refusal-probe wall, DEV',f"{p['probe_seconds']:.6f} s"],['Reason generation wall, DEV',f"{p['reason_seconds']:.6f} s"],['Generated reason tokens',p['reason_tokens']],['Reason tokens / second',p['reason_tokens']/p['reason_seconds'] if p['reason_seconds'] else 'N/A'],['Contract validity',fm['contract_validity']],['Macro relation F1',fm['macro_relation_f1']],['Accepted outcomes',f"{round(fm['accepted_semantic_outcomes']*60)}/60"],['Evidence F1',fm['evidence_f1']],['Refusal precision / recall',f"{fm['refusal_precision']} / {fm['refusal_recall']}"],['Over-refusal',fm['over_refusal_rate']],['Substantive non-refusal coverage',fm['substantive_non_refusal_coverage']]]),'',
            table(['Class','Recall'],fm['per_class_recall'].items()),'',table(['Catastrophic category','Count'],fm['catastrophic'].items()),'',
            'Frozen gates: contract1, macro relation F1≥0.75, every class recall≥0.60, acceptance≥0.70, evidence F1≥0.85, refusal precision≥0.90, refusal recall≥0.80, over-refusal≤0.05, substantive non-refusal coverage≥0.90, all catastrophes0. No gate or historical scorer was changed.','',
            table(['Additional non-regression requirement','Passed'],x['nonregression'].items()),'',
            '## Performance','',table(['Measure','Result'],[['Peak allocated VRAM',f"{p['peak_vram_allocated']/2**30:.6f} GiB"],['Peak reserved VRAM',f"{p['peak_vram_reserved']/2**30:.6f} GiB"],['Mean sampled GPU utilization',p['gpu_utilization_mean']],['Mean sampled process CPU percent',p['cpu_percent_mean']],['Peak process RSS',f"{p['peak_rss']/2**30:.6f} GiB"],['Peak host RAM used',f"{p['peak_host_ram']/2**30:.6f} GiB"]]),'',
            'GPU/CPU/RAM sampling spans the remote execution process; CPU percent can exceed 100% across cores. The full-DEV timing includes fresh feature identity checks, routing, generation, fsync and scoring; reason/probe timings isolate generation calls. Controls are excluded from DEV throughput figures.','',
            '## Diagnosis and selection','', '**'+x['diagnostic']+'**','',
            'Diagnostic rule: full success; otherwise refusal/evidence routing regression if those metrics regress; otherwise explanation failure when raw-head relation gates pass; otherwise classifier failure. Contract-invalid explanations can lower valid non-refusal coverage without changing refusal routing. That coverage gate still fails; it is not hidden or renamed. Raw-head relation requirements use macro F1≥0.75 and all five recalls≥0.60. The diagnostic label does not replace the integrated verdict.','',
            'Failed required gates:','', '```json',json.dumps(x['failed_gates'],indent=2),'```','',
            ('The update200 head and frozen-component binding are eligible under this experiment. A governed system test remains separately unauthorized.' if x['verdict']=='AUDITOR_LINEAR_PROBE_PASS' else 'No passing integrated Auditor is selected. The only candidate completed and failed required gates. No second head, parameter search, pooling change or classifier-specific LoRA fallback is authorized.'),'']
        if x['verdict']=='AUDITOR_LINEAR_PROBE_FAIL':
            diagnosis=read(B/'FAILURE_DIAGNOSIS.json')
            lines+=['### Local failure diagnosis only','',
                f"{len(diagnosis['failed_rows'])} nonaccepted rows: {diagnosis['wrong_relations']} wrong relations and {diagnosis['correct_relation_failed_reason']} correct relations with nonmatching reasons. These are unchanged frozen-scorer outcomes, not a semantic rescore.",'',
                'The head fits TRAIN perfectly but generalizes incompletely to canonical DEV. Relative to historical step120, raw relation accuracy rises from 29/60 to 41/60 and macro F1 from 0.434966 to 0.679320. Integrated acceptance rises only from 28/60 to 32/60. Prediction counts are MATCH5, DIVERGENCE9, OMISSION7, ADDITION27, INSUFFICIENT_EVIDENCE12: all five classes appear, but ADDITION remains overpredicted. This single run does not establish a causal explanation for the generalization gap or justify automatically adapting the backbone.','',
                'All 48 substantive rows receive reasons; no head/veto routing disagreement occurs. Rows137 and142 fail the unchanged contract with “Unselected citation in fidelity reason”: row137 mentions context-only REF-9999, and row142 mentions REF-40566, which is not supplied for that row. Their serialized ref_ids are still exactly correct. Thus evidence-ID F1 remains1 while contract validity is58/60 and valid substantive coverage is46/48. The frozen invented_evidence catastrophe checks ref_ids, not free-text citations; its count remains0. No reason or citation is repaired.','',
                'The two confident-wrong catastrophes are rows052 and162, both OMISSION→DIVERGENCE. Among the nine correct-class reason rejections, row046 gives a semantically aligned shorter quotation but fails the exact expected-reason string; rows156 and161 reverse replacement direction; rows047,050,272,275,277,282 identify wrong, structural or incomplete content. This annotation is descriptive and changes no score.','',
                'Full per-row expected/generated reasons and failure flags are in [FAILURE_DIAGNOSIS.json](auditor_linear_probe_run/FAILURE_DIAGNOSIS.json). Stop here. The classifier-specific LoRA fallback and governed system test remain unauthorized.','']
    lines+=['## Independent verification and next action','',
        'Local recomputation uses saved feature/head tensors and raw intermediate outputs, not model generation. It checks feature hashes and TRAIN-only statistics; zero initial head and 200-update logs; frozen-weight state hashes and parameter-state receipts; raw/scored identity; deterministic controls; logits/classes; refusal/reason parsing; assembled token accounting; frozen metrics and non-regression gates. Historical Auditor and Producer evidence text hashes remain unchanged; Producer binary preservation uses metadata only.','',
        'For FAIL: stop and diagnose locally only. For INDETERMINATE: address only the recorded invalidating issue in a future authorized action. For PASS: no automatic governed system test. No fallback execution.','',
        '`PRODUCER_STATUS=PRESERVED_UNEXECUTED`','', '`PROTECTED_RECEIPT_STATUS=UNCONSUMED`','',
        'One cloud instance and one GPU only. No new data, Producer execution/training, protected access, folds1–4, paid inference API, full pipeline, governed Producer+Auditor run, multi-round, second candidate, fallback or push. No backbone or LoRA update. Zero billable resources remain.','',
        'Evidence: [recomputed results](auditor_linear_probe_run/RECOMPUTED_RESULTS.json); [handoff](auditor_linear_probe_run/HANDOFF.md). Binary features and head artifacts remain local and are hash-bound in the evidence manifest.','']
    (ROOT/'docs/fix/AUDITOR_LINEAR_PROBE_RESULTS.md').write_text('\n'.join(lines),encoding='utf8')
    handoff=['# Auditor linear probe handoff','',x['verdict'],'',
        'Tested source: '+m['source_commit']+'. Design: 25f7dc0. Historical canonical Auditor FAIL remains immutable.','',
        'Result commit subject: Record bounded Auditor linear-probe outcome and verified cleanup.','',
        'Provider-confirmed termination: '+t['utc']+'. Zero resources remain; ephemeral SSH registration/key removed.','',
        'Read ../AUDITOR_LINEAR_PROBE_RESULTS.md and RECOMPUTED_RESULTS.json. No automatic continuation, new head or fallback. Producer168 remains unexecuted; protected receipt unconsumed.','']
    (B/'HANDOFF.md').write_text('\n'.join(handoff),encoding='utf8')

if __name__=='__main__':report()
